import { useEffect, useMemo, useRef, useState } from 'react'
import { useQuery, useQueryClient } from '@tanstack/react-query'
import { fetchMe, logout, requestNonce, verifyLogin } from '../lib/auth-api'
import { connectAccount, deviceIdentifier, isInsideNimiqPay, nimiqPayDeepLink, signMessage, sendRelayHandoff, NimiqPayError } from '../lib/nimiq'
import { StationController } from '../station/controller'
import { RaceView, type RaceSession } from '../station/RaceView'
import { RelayAudio } from '../station/audio'
import { mountStation } from '../station/visuals'
import { readTransfer, saveTransfer } from '../station/transfer-store'
import * as station from '../station/api'
import * as api from './api'
import { shareJourneyCard } from './share-card'
import { mountGlobe, type GlobeHandle } from './globe'
import '../station/station.css'
import './network.css'

const worldNames = { coast:'Sunbreak Coast', alpine:'Cloudline Alps', metro:'Midnight Metro', solar:'Solar Frontier', ocean:'Ocean Skyway' }
const ago = (time:number) => { const seconds=Math.max(0,Math.floor((Date.now()-time)/1000));return seconds<60?'Just now':seconds<3600?`${Math.floor(seconds/60)}m`:seconds<86400?`${Math.floor(seconds/3600)}h`:`${Math.floor(seconds/86400)}d` }
const countryName = (code:string|null) => code ? new Intl.DisplayNames(['en'],{type:'region'}).of(code)??code : 'Location not shared'
const compactWallet=(wallet:string)=>`${wallet.slice(0,8)}…${wallet.slice(-6)}`
async function share(title:string,path:string){const url=new URL(path,location.origin).href;if(navigator.share)await navigator.share({title,url});else await navigator.clipboard.writeText(url)}
function initialPanel(){const parts=location.pathname.split('/').filter(Boolean);if(['relay','r','journey'].includes(parts[0]??''))return'journey';if(parts[0]==='invite')return'invite';return ['proof','daily','crews','inbox','profile','vault','create','rivals','home','privacy'].includes(parts[0]??'')?parts[0]!:null}

export function NetworkApp(){
 const client=useQueryClient(),host=useRef<HTMLDivElement>(null),homeHost=useRef<HTMLDivElement>(null),globe=useRef<GlobeHandle|null>(null),audio=useRef<RelayAudio|null>(null)
 const me=useQuery({queryKey:['me'],queryFn:fetchMe,retry:false})
 const publicState=useQuery({queryKey:['network-public'],queryFn:api.loadPublicNetwork,refetchInterval:15000,retry:1})
 const accountState=useQuery({queryKey:['network'],queryFn:api.loadNetwork,enabled:!!me.data,refetchInterval:10000,retry:1})
 const profile=useQuery({queryKey:['station'],queryFn:station.loadStation,enabled:!!me.data,retry:1})
 const data=accountState.data??publicState.data
 const [panel,setPanel]=useState<string|null>(initialPanel),[selected,setSelected]=useState<string|null>(()=>['relay','r','journey'].includes(location.pathname.split('/')[1]??'')?location.pathname.split('/')[2]??null:location.pathname.startsWith('/proof/relay/')?location.pathname.split('/')[3]??null:null)
 const [race,setRace]=useState<RaceSession|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[arrival,setArrival]=useState<{batonId:string;key:string}|null>(null)
 const [title,setTitle]=useState(''),[recipient,setRecipient]=useState(''),[mode,setMode]=useState<'quick'|'global'|'crew'>('quick'),[bestOf,setBestOf]=useState<3|5>(3),[consent,setConsent]=useState(false),[sound,setSound]=useState(true)
 const incoming=data?.inbox.find(n=>n.type==='incoming_baton'&&n.readAt===null)
 const selectedId=selected??incoming?.batonId??null
 const currentPanel=panel??(incoming?'journey':null)
 const batonQuery=useQuery({queryKey:['baton',selectedId],queryFn:()=>api.loadBaton(selectedId!),enabled:!!selectedId,refetchInterval:10000,retry:1})
 const detail=batonQuery.data,baton=detail?.baton??data?.batons.find(b=>b.id===selectedId||b.code===selectedId)
 const inviteToken=location.pathname.startsWith('/invite/')?location.pathname.split('/')[2]??'':''
 const invite=useQuery({queryKey:['invite',inviteToken],queryFn:()=>api.openNetworkInvite(inviteToken),enabled:!!inviteToken,retry:false})
 const refresh=()=>{void client.invalidateQueries({queryKey:['network']});void client.invalidateQueries({queryKey:['network-public']});void client.invalidateQueries({queryKey:['baton']});void client.invalidateQueries({queryKey:['station']})}
 async function act(action:()=>Promise<unknown>){if(busy)return;setBusy(true);setMessage('');try{await action()}catch(cause){if(cause instanceof DOMException&&cause.name==='AbortError')return;setMessage(cause instanceof Error?cause.message:'Please try again.')}finally{setBusy(false)}}
 const choose=(id:string)=>{setSelected(id);setPanel('journey')}
 const globeBatons=useMemo(()=>data?.batons.map(b=>({id:b.id,name:b.title,mode:b.mode,holderName:b.holder.name,handoffCount:b.handoffCount,route:b.route??(b.id===detail?.baton.id?[{countryCode:b.origin.country},...detail.handoffs.map(h=>({countryCode:h.to.country}))]:[{countryCode:b.origin.country},...(b.handoffCount?[{countryCode:b.holder.country}]:[])] )}))??[],[data?.batons,detail])
 useEffect(()=>{audio.current=new RelayAudio();return()=>audio.current?.dispose()},[])
 useEffect(()=>{if(!host.current||race||currentPanel==='home')return;globe.current=mountGlobe(host.current,{batons:[],onSelect:choose});return()=>{globe.current?.dispose();globe.current=null}},[race,currentPanel==='home'])
 useEffect(()=>{globe.current?.update({batons:globeBatons,selectedId:baton?.id??selectedId,onSelect:choose,arrival:arrival??(incoming?.batonId?{batonId:incoming.batonId,key:incoming.id}:null)})},[globeBatons,selectedId,baton?.id,arrival,incoming])
 useEffect(()=>{if(currentPanel!=='home'||!homeHost.current||race)return;return mountStation(homeHost.current,destination=>{const panels:Record<string,string>={quick:'create',global:'journeys',crew:'crews',customize:'profile',gallery:'vault',rival:'rivals',rankings:'daily',chronicles:'vault'};setPanel(panels[destination]??destination)},{...profile.data?.profile.equipped,handoffs:profile.data?.profile.handoffs??0})},[currentPanel,race,profile.data?.profile])
 useEffect(()=>{const socket=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/network`);socket.onmessage=()=>{void client.invalidateQueries({queryKey:['network']});void client.invalidateQueries({queryKey:['network-public']});void client.invalidateQueries({queryKey:['baton']})};return()=>socket.close()},[client])
 useEffect(()=>{if(!me.data)return;let last=performance.now();const heartbeat=()=>{const now=performance.now();if(!document.hidden){const seconds=Math.min(30,Math.floor((now-last)/1000));if(seconds>0)void api.networkHeartbeat(seconds).catch(()=>undefined)}last=now};const timer=setInterval(heartbeat,15000);const visibility=()=>{last=performance.now()};document.addEventListener('visibilitychange',visibility);return()=>{clearInterval(timer);document.removeEventListener('visibilitychange',visibility)}},[me.data])
 async function login(){await connectAccount();const deviceId=consent?await deviceIdentifier('Fair play: identify repeated Daily attempts without storing your device identifier.'):undefined;const challenge=await requestNonce(),signed=await signMessage(challenge.message);const result=await verifyLogin({nonce:challenge.nonce,...signed,...(deviceId?{deviceId}:{})});client.setQueryData(['me'],result.player);setPanel(inviteToken?'invite':null);refresh()}
 async function ride(options:{batonId?:string;daily?:boolean;practice?:boolean;ghostRunId?:string}={practice:true},watch=false){await act(async()=>{await audio.current?.unlock();let issued:api.IssuedRace|null=null;let ghost:api.CanonicalGhost|null=null;if(options.ghostRunId)ghost=await api.loadVerifiedReplay(options.ghostRunId);if(me.data&&!watch)issued=await api.issueNetworkRace(options);const config=issued?.config??ghost?.config??{engineVersion:'4',challenge:'station-race',challengeVersion:'4',seed:options.daily?data?.daily.seed??`daily-${new Date().toISOString().slice(0,10)}-v4`:crypto.randomUUID(),world:options.daily?data?.daily.world??'coast':'coast'};ghost=issued?.ghost??ghost;const controller=new StationController(config,!watch&&ghost?{trace:ghost.inputTrace,name:ghost.name}:undefined,watch&&ghost?{playbackTrace:ghost.inputTrace}:undefined);setRace({controller,issued})})}
 function transferred(intent:api.HandoffIntent){const found=data?.batons.find(b=>b.id===race?.issued?.batonId);if(found){setSelected(found.id);setArrival({batonId:found.id,key:intent.id});setPanel('journey')}refresh()}
 const couriers=(data?.runners??[]).filter(r=>r.id!==me.data?.id).map(r=>({id:r.id,name:r.name,score:0,xp:0}))
 if(race)return <RaceView key={race.issued?.runId??race.controller.config.seed} session={race} audio={audio.current} profile={profile.data?.profile} couriers={couriers} network={data?.network??'TestAlbatross'} onSubmit={api.submitNetworkRace} onPrepare={api.prepareNetworkHandoff} onAttempt={intent=>api.attemptNetworkHandoff(intent.id)} onCancel={intent=>api.cancelNetworkHandoff(intent.id)} onConfirm={api.confirmNetworkHandoff} onTransfer={transferred} onReplay={()=>{const ghost=race.issued?.ghost;setRace(null);void ride({practice:true,...(ghost?{ghostRunId:ghost.runId}:{})})}} onExit={()=>{setRace(null);refresh()}} />
 const needLogin=<div className="network-empty"><p>Set up your courier to receive and pass batons.</p>{isInsideNimiqPay()?<button className="network-button primary" onClick={()=>setPanel('activate')}>Set up courier</button>:<a className="network-button primary" href={nimiqPayDeepLink(location.href)}>Open in Nimiq Pay</a>}</div>
 return <main className="network-app">
  <div className="network-globe" ref={host} aria-label="Interactive Earth showing real relay journeys" />
  {currentPanel==='home'&&<div className="network-globe" ref={homeHost} />}
  <header className="network-topbar"><a className="network-brand" href="/">NIM RELAY</a><div className="network-actions"><span className="network-network">{data?.network==='MainAlbatross'?'Nimiq mainnet':'Test network'}</span><button className="network-button" aria-pressed={sound} onClick={()=>{setSound(!sound);audio.current?.toggle()}}>{sound?'Sound on':'Sound off'}</button><button className="network-button" onClick={()=>setPanel(me.data?'profile':'activate')}>{me.data?profile.data?.profile.name??me.data.handle:'Join the relay'}</button></div></header>
  {!currentPanel&&<section className="network-intro"><h1>How far can<br/>one NIM travel?</h1><p>Receive it. Beat the ghost. Pass it on.</p><div className="network-actions"><button className="network-button primary" onClick={()=>setPanel('journeys')}>Explore journeys</button><button className="network-button" onClick={()=>void ride()}>Try a relay leg</button></div><div className="network-stats"><span><b>{data?.metrics.qualifiedHandoffs??'—'}</b> confirmed handoffs</span><span><b>{data?.metrics.transactingWallets??'—'}</b> transacting wallets</span></div><p className="network-muted">{data?.network==='TestAlbatross'?'Testnet activity. Excluded from mainnet usage.':'Real wallet transfers. No wagers or prizes.'} Countries are approximate, consented network observations.</p></section>}
  <nav className="network-nav" aria-label="Relay navigation">{[['journeys','World'],['inbox',`Your turns${incoming?' •':''}`],['daily','Daily'],['crews','Crews'],['rivals','Rivals'],['home','Station'],['vault','Baton Vault']].map(([key,label])=><button key={key} aria-current={currentPanel===key?'page':undefined} onClick={()=>setPanel(key!)}>{label}</button>)}</nav>
  {(message||publicState.isError||accountState.isError)&&<div className="network-toast" role="status">{message||'The relay network is temporarily unavailable. Your wallet and saved journeys are unchanged.'}<button aria-label="Dismiss message" onClick={()=>setMessage('')}>×</button></div>}
  {currentPanel&&currentPanel!=='home'&&<section className={`network-panel ${currentPanel==='proof'?'network-proof':''}`} aria-label={currentPanel}><header className="network-panel-header"><h2>{({journeys:'Living journeys',journey:baton?.title??'Journey',inbox:'Your reason to return',daily:'Daily Circuit',crews:'Keep it moving together',rivals:'Two routes. One rivalry.',profile:'Your courier',vault:'Baton Vault',activate:'Become a courier',create:'Start a journey',invite:'You’re invited',proof:'Proof of the relay',privacy:'Your privacy'} as Record<string,string>)[currentPanel]??currentPanel}</h2><button aria-label="Close panel" onClick={()=>{setPanel(null);if(incoming)void api.markNotificationRead(incoming.id).then(refresh)}}>×</button></header>
   {currentPanel==='activate'&&<>{needLogin&&<><p>Your wallet stays in Nimiq Pay. Sign in once; approve a transfer only when you pass a baton.</p><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Allow a pseudonymous device signal for fair play. The raw identifier is never stored.</label>{isInsideNimiqPay()?<button className="network-button primary" disabled={busy} onClick={()=>void act(login)}>{busy?'Waiting for Nimiq Pay…':'Set up my courier'}</button>:<a className="network-button primary" href={nimiqPayDeepLink(location.href)}>Open in Nimiq Pay</a>}<button className="network-button" onClick={()=>void ride()}>Practice without signing in</button><a href="/privacy">Privacy details</a></>}</>}
   {(currentPanel==='journeys'||currentPanel==='vault')&&<>{data?.batons.length?data.batons.filter(b=>currentPanel!=='vault'||b.status!=='active'||b.handoffCount>0).map(b=><button className="network-journey" key={b.id} onClick={()=>choose(b.id)}><span className="network-baton-mark">⬡</span><span><strong>{b.title}</strong><small>{b.mode} · {b.holder.name} carries {b.value/100000} NIM</small><small>{b.handoffCount} handoffs · {ago(b.createdAt)} old · {b.status}</small></span></button>):<div className="network-empty"><h3>The next journey starts with someone.</h3><p>No baton journeys have started on this network yet. Create one and invite your next runner.</p></div>}<button className="network-button primary" onClick={()=>setPanel(me.data?'create':'activate')}>Start a relay</button><a className="network-button" href="/proof">View public proof</a></>}
   {currentPanel==='create'&&(me.data?<form onSubmit={e=>{e.preventDefault();void act(async()=>{const result=await api.createBaton({title,mode,...(recipient?{recipient}:{}),bestOf,...(profile.data?.profile.crewId?{crewId:profile.data.profile.crewId}:{})});refresh();choose(result.baton.id)})}}><label>Journey name<input required minLength={3} maxLength={60} value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Relay type<select value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="quick">Quick — a friend match</option><option value="global">Global — an open journey</option><option value="crew">Crew — your shared baton</option></select></label>{mode==='quick'&&<><RunnerPicker runners={data?.runners??[]} self={me.data.id} value={recipient} onChange={setRecipient}/><label>Match length<select value={bestOf} onChange={e=>setBestOf(Number(e.target.value)===5?5:3)}><option value={3}>Best of 3</option><option value={5}>Best of 5</option></select></label></>}<p>Start with 1 NIM in your wallet. Each pass transfers that amount to the next courier. Scores award recognition, never money.</p><button className="network-button primary" disabled={busy}>Create journey</button></form>:needLogin)}
   {currentPanel==='journey'&&baton&&<><p className="network-muted">{baton.code} · {baton.mode} · {baton.network} · {ago(baton.createdAt)} old</p>{incoming?.batonId===baton.id&&<div className="network-arrival"><h3>{incoming.title}</h3><p>{incoming.body}</p><p>Your previous runner’s verified ghost is waiting.</p></div>}<h3>{baton.holder.name} carries the baton</h3><p>{baton.handoffCount} confirmed handoffs · {baton.lineage.runners} couriers · {baton.lineage.countries.length} network-observed countries</p><p>{baton.value/100000} NIM · {compactWallet(baton.holder.wallet)}</p>{baton.status==='stranded'&&<p>This baton is stranded with its current holder. NIM Relay cannot move their funds. The holder can return and continue.</p>}{baton.quick&&<><h3>{baton.quick.rounds} of {baton.quick.bestOf} rounds played</h3>{baton.quick.players.map(id=><p key={id}>{data?.runners.find(r=>r.id===id)?.name??'Courier'}: {baton.quick!.scores[id]??0}</p>)}<p>Each round returns the baton to its origin. No wager or monetary prize.</p>{baton.status==='completed'&&<button className="network-button primary" disabled={busy} onClick={()=>void act(async()=>{const result=await api.rematchBaton(baton.id);refresh();choose(result.baton.id)})}>Rematch</button>}</>}
    <div className="network-actions">{baton.holder.id===me.data?.id&&baton.status!=='completed'&&<button className="network-button primary" disabled={busy} onClick={()=>void ride({batonId:baton.id})}>Carry this leg</button>}<button className="network-button" disabled={busy} onClick={()=>void ride({practice:true,...(baton.previousRunId?{ghostRunId:baton.previousRunId}:{})})}>Race the ghost in practice</button><button className="network-button" onClick={()=>void act(()=>share(baton.title,`/relay/${baton.code}`))}>Share journey</button>{detail&&<button className="network-button" onClick={()=>void act(()=>shareJourneyCard(detail))}>Share journey card</button>}{baton.holder.id===me.data?.id&&<button className="network-button" disabled={busy} onClick={()=>void act(async()=>{const invitation=await api.createNetworkInvite(baton.id);await share(`Carry ${baton.title}`,invitation.url);setMessage('Invite link ready to share.')})}>Invite next runner</button>}</div>
    {data?.pendingHandoff?.batonId===baton.id&&<RecoverTransfer intent={data.pendingHandoff} onDone={()=>{setArrival({batonId:baton.id,key:crypto.randomUUID()});refresh()}}/>}
    <h3>The journey</h3><ol className="network-route-list"><li><strong>{baton.origin.name} started the baton</strong><span>{countryName(baton.origin.country)}</span><small>Origin wallet: {compactWallet(baton.origin.wallet)}. Continuity starts with the first confirmed pass.</small></li>{detail?.handoffs.map(h=><li key={h.id}><strong>{h.from.name} → {h.to.name}</strong><span>{countryName(h.from.country)} → {countryName(h.to.country)}</span><small>{new Date(h.at).toLocaleString()} · {h.value/100000} NIM · Handoff {h.leg}</small><div className="network-actions"><button className="network-button" onClick={()=>void ride({ghostRunId:h.runId},true)}>Watch verified ride</button><a href={`/proof/relay/${baton.code}#${h.txHash}`}>Transaction proof</a></div></li>)}</ol><p className="network-muted">Countries reflect consenting couriers’ network connections, not blockchain-verified physical locations. Unknown locations appear outside the globe.</p></>}
   {currentPanel==='inbox'&&(me.data?<>{data?.inbox.length?data.inbox.map(n=><button className="network-journey" key={n.id} onClick={()=>{void api.markNotificationRead(n.id).then(refresh);if(n.batonId)choose(n.batonId);else setPanel('daily')}}><span>⬡</span><span><strong>{n.title}</strong><small>{n.body}</small><small>{ago(n.createdAt)} ago</small></span></button>):<p>Your incoming batons, ghost battles, and rematches arrive here.</p>}<button className="network-button primary" onClick={()=>setPanel('daily')}>Today’s Daily Circuit</button>{data?.crews.filter(c=>c.members.some(m=>m.id===me.data?.id)&&c.todayHandoffs===0).map(c=><button className="network-journey" key={c.id} onClick={()=>setPanel('crews')}><span><strong>{c.name} needs a pass today</strong><small>{c.streak} day streak · Deadline {new Date(c.deadline).toLocaleTimeString()}</small></span></button>)}</>:needLogin)}
   {currentPanel==='daily'&&<><p>{data?.daily.date} · {worldNames[data?.daily.world??'coast']}</p><h3>One route. Everyone rides the same line.</h3><p>One official attempt per wallet each day. Unlimited practice. All ranked scores are replayed by the server.</p><div className="network-actions"><button className="network-button primary" disabled={busy||!!data?.daily.officialRunId} onClick={()=>me.data?void ride({daily:true}):setPanel('activate')}>{data?.daily.officialRunId?'Official attempt started':'Ride official Daily'}</button><button className="network-button" onClick={()=>void ride({daily:true,practice:true})}>Practice</button><button className="network-button" onClick={()=>void act(()=>share('NIM Relay Daily Circuit','/daily'))}>Share Daily</button></div><h3>Official leaderboard</h3>{data?.daily.leaderboard.length?data.daily.leaderboard.map((entry,i)=><div className="network-row" key={entry.runId}><b>{i+1}</b><span>{entry.player.name}</span><strong>{entry.score.toLocaleString()}</strong><button className="network-button" onClick={()=>void ride({ghostRunId:entry.runId},true)}>Watch</button></div>):<p>No official scores yet today.</p>}</>}
   {currentPanel==='crews'&&<>{me.data?<form onSubmit={e=>{e.preventDefault();void act(async()=>{await api.createNetworkCrew(title);refresh();setTitle('')})}}><label>Crew name or invite code<input value={title} onChange={e=>setTitle(e.target.value)}/></label><div className="network-actions"><button className="network-button primary" disabled={busy||title.trim().length<3}>Create crew</button><button type="button" className="network-button" disabled={busy||!title} onClick={()=>void act(async()=>{await api.joinNetworkCrew(title);refresh();setTitle('')})}>Join with code</button></div></form>:needLogin}{data?.crews.map(c=><section className="network-crew" key={c.id}><h3>{c.name}</h3><p>{c.streak} day streak · Best {c.bestStreak} · {c.todayHandoffs} passes today</p><p>Different crew members must complete a real handoff by {new Date(c.deadline).toLocaleTimeString()}.</p>{c.members.map(m=><div className="network-row" key={m.id}><span>{m.name}</span><span>{c.contributions[m.id]??0} contributions</span></div>)}<p>Invite code: <strong>{c.code}</strong></p>{c.batonIds.map(id=><button className="network-button" key={id} onClick={()=>choose(id)}>Open crew baton</button>)}{c.members.some(m=>m.id===me.data?.id)&&<button className="network-button primary" onClick={()=>void act(async()=>{const result=await api.createBaton({mode:'crew',title:`${c.name} relay`,crewId:c.id});refresh();choose(result.baton.id)})}>Start crew baton</button>}</section>)}</>}
   {currentPanel==='rivals'&&<>{me.data?<form onSubmit={e=>{e.preventDefault();void act(async()=>{await api.createNetworkRival({title,opponent:recipient,target:10});refresh()})}}><label>Rivalry name<input required minLength={3} value={title} onChange={e=>setTitle(e.target.value)}/></label><RunnerPicker runners={data?.runners??[]} self={me.data.id} value={recipient} onChange={setRecipient}/><p>Two independent 1 NIM batons. First to 10 confirmed handoffs earns the title. No shared funds or prizes.</p><button className="network-button primary" disabled={busy}>Start rivalry</button></form>:needLogin}{data?.rivals.map(r=><section className="network-crew" key={r.id}><h3>{r.title}</h3><p>{r.scores[0]} — {r.scores[1]} · Target {r.target}</p>{r.batonIds.map((id,i)=><button className="network-button" key={id} onClick={()=>choose(id)}>Team {i+1} route</button>)}<p>{r.winnerId?'Competition complete':`Ends ${new Date(r.endsAt).toLocaleDateString()}`}</p></section>)}</>}
   {currentPanel==='invite'&&<>{invite.data?<><h3>{invite.data.from.name} wants you in the relay.</h3><p>Receive 1 NIM, race their verified ghost, and carry the journey forward.</p>{me.data?<button className="network-button primary" disabled={busy} onClick={()=>void act(async()=>{const result=await api.claimNetworkInvite(inviteToken);refresh();choose(result.baton.id)})}>Accept invitation</button>:needLogin}</>:<p>{invite.isError?'This invitation is unavailable or expired.':'Opening invitation…'}</p>}</>}
   {currentPanel==='profile'&&(profile.data?<><h3>{profile.data.profile.name}</h3><p>@{profile.data.profile.handle}</p><p>Level {profile.data.profile.level} · {profile.data.profile.seasonRank} · {profile.data.profile.xp} XP</p><p>{profile.data.profile.handoffs} handoffs · {profile.data.profile.runs} rides</p><h3>Your history</h3>{data?.batons.filter(b=>b.origin.id===me.data?.id||b.holder.id===me.data?.id).map(b=><button className="network-journey" key={b.id} onClick={()=>choose(b.id)}>{b.title} · {b.handoffCount} passes</button>)}<h3>Achievements</h3>{profile.data.profile.achievements.map(a=><p key={a}>⬡ {a}</p>)}<label>Courier name<input value={title} onChange={e=>setTitle(e.target.value)}/></label><button className="network-button" onClick={()=>void act(async()=>{await station.customizeCourier({name:title});refresh()})}>Save name</button><label><input type="checkbox" checked={data?.countryConsent??false} onChange={e=>void act(async()=>{await api.setCountryConsent(e.target.checked);refresh()})}/> Share my approximate network country on relay routes</label><p className="network-muted">Optional. No precise location or raw IP is saved.</p><h3>Courier locker</h3><div className="network-locker">{profile.data.cosmetics.map(c=><button className="network-button" disabled={busy||!profile.data!.profile.unlocked.includes(c.id)||profile.data!.profile.equipped[c.category]===c.id} key={c.id} onClick={()=>void act(async()=>{await station.customizeCourier({category:c.category,cosmetic:c.id});refresh()})}>{c.name} · {profile.data!.profile.unlocked.includes(c.id)?'Equip':`${c.xp} XP`}</button>)}</div><button className="network-button" onClick={()=>void act(async()=>{await logout();client.setQueryData(['me'],null);client.removeQueries({queryKey:['network']});client.removeQueries({queryKey:['station']});setPanel(null)})}>Sign out</button></>:needLogin)}
   {currentPanel==='proof'&&<Proof data={data} detail={detail} onJourney={setSelected} onWatch={id=>void ride({ghostRunId:id},true)}/>}
   {currentPanel==='privacy'&&<><p>Your Nimiq private keys stay in Nimiq Pay. Every transfer needs your approval. The app cannot recover funds from an absent holder.</p><p>We store linked wallet addresses, courier profiles, verified game inputs, public handoff transactions, and session records. Optional device identifiers are hashed before storage. We do not store raw IP addresses.</p><p>Country sharing is optional. Countries are approximate network observations and can be affected by VPNs. Turn sharing off in your profile.</p><p>Wallets are not proof of unique people. Testnet activity is displayed separately from mainnet usage. On-chain transaction history cannot be deleted.</p><a href="/proof">Public proof and measurement definitions</a></>}
  </section>}
  {currentPanel==='home'&&<section className="network-intro"><h1>Your Relay Station</h1><p>Choose your next journey. Your courier and the baton’s history come with you.</p><div className="network-actions"><button className="network-button primary" onClick={()=>setPanel('journeys')}>Journey map</button><button className="network-button" onClick={()=>setPanel('profile')}>Courier locker</button><button className="network-button" onClick={()=>setPanel('daily')}>Daily Circuit</button></div></section>}
 </main>
}
function RunnerPicker({runners,self,value,onChange}:{runners:api.NetworkRunner[];self:string;value:string;onChange:(value:string)=>void}){return <label>Next courier<select value={value} onChange={e=>onChange(e.target.value)}><option value="">Choose a linked courier</option>{runners.filter(r=>r.id!==self).map(r=><option value={r.id} key={r.id}>{r.name} (@{r.handle})</option>)}</select><input aria-label="Courier handle" placeholder="Or enter their handle" value={value} onChange={e=>onChange(e.target.value)}/></label>}
function Proof({data,detail,onJourney,onWatch}:{data:api.NetworkSnapshot|undefined;detail:api.BatonDetail|undefined;onJourney:(id:string)=>void;onWatch:(id:string)=>void}){if(!data)return <p>Loading independently verified records…</p>;const m=data.metrics;return <><p>{data.network} · Engine 4 · {data.network==='TestAlbatross'?'Controlled/test evidence. Not real mainnet traction.':'Mainnet activity'}</p><dl>{Object.entries({ 'Linked wallets':m.linkedWallets,'Transacting wallets':m.transactingWallets,'Qualified handoffs':m.qualifiedHandoffs,'Mainnet handoffs':m.mainnetHandoffs,'Testnet handoffs':m.testnetHandoffs,'Invites created':m.invites,'Invites accepted':m.inviteConversions,'Returning wallets':m.returningWallets,'Quick rematches':m.quickRematches,'Crew active days':m.crewActiveDays,'Official Daily attempts':m.dailyAttempts,'Foreground seconds':m.foregroundSeconds }).map(([label,value])=><div className="network-row" key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>{m.definitions.map(d=><p className="network-muted" key={d}>{d}</p>)}<h3>Canonical journeys</h3>{data.batons.map(b=><button className="network-journey" key={b.id} onClick={()=>onJourney(b.id)}>{b.title} · {b.code} · {b.handoffCount} handoffs</button>)}{detail?.handoffs.map(h=><article key={h.id} id={h.txHash}><h3>Handoff {h.leg}</h3><p>{h.from.wallet} → {h.to.wallet}</p><p>{h.value} Luna · Block {h.blockNumber} · {h.confirmations} confirmations</p><p>Transaction: <code>{h.txHash}</code></p><p>Replay result: <code>{h.resultHash}</code></p><button className="network-button" onClick={()=>onWatch(h.runId)}>Watch canonical replay</button></article>)}<p>NIM is fungible. A baton is an ordered value-transfer lineage, not a uniquely identifiable coin.</p></>}
function RecoverTransfer({intent,onDone}:{intent:api.NetworkHandoffIntent;onDone:()=>void}){const [hash,setHash]=useState(intent.txHash??''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');useEffect(()=>{let active=true;void readTransfer(intent.id).then(record=>{if(active&&record?.hash)setHash(record.hash)}).catch(error=>{if(active)setMessage(String(error))});return()=>{active=false}},[intent.id]);async function recover(){setBusy(true);try{let tx=hash;if(!tx){const saved=await readTransfer(intent.id);if(intent.state!=='prepared'&&saved?.state!=='ready')throw new Error('Check your wallet activity and paste the transaction reference. An earlier request may have been broadcast.');await saveTransfer({id:intent.id,hash:null,state:'attempting'});await api.attemptNetworkHandoff(intent.id);tx=await sendRelayHandoff(intent);setHash(tx);await saveTransfer({id:intent.id,hash:tx,state:'sent'})}const result=await api.confirmNetworkHandoff(intent.id,tx);if(result.status==='verified'){await saveTransfer({id:intent.id,hash:tx,state:'verified'});onDone()}else setMessage(result.reason??'Awaiting network confirmation.')}catch(error){if(error instanceof NimiqPayError&&error.approvalDeclined)await saveTransfer({id:intent.id,hash:null,state:'ready'});setMessage(error instanceof Error?error.message:'Could not check transfer')}finally{setBusy(false)}}return <section className="network-arrival"><h3>Pass to {intent.recipientName}</h3><p>{intent.value/100000} NIM on {intent.network}. Your prepared recipient and amount are locked.</p><input aria-label="Transaction reference" placeholder="Transaction reference, if already sent" value={hash} onChange={e=>setHash(e.target.value)}/><button className="network-button primary" disabled={busy} onClick={()=>void recover()}>{hash?'Check confirmation':intent.state==='prepared'?'Approve in Nimiq Pay':'Recover transfer'}</button>{intent.state==='prepared'&&<button className="network-button" disabled={busy} onClick={()=>{setBusy(true);void api.cancelNetworkHandoff(intent.id).then(onDone).catch(e=>setMessage(String(e))).finally(()=>setBusy(false))}}>Cancel this unattempted pass</button>}{message&&<p role="status">{message}</p>}</section>}
