packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workers-types@5.20260901.1'
  - miniflare@5.20260831.0-alpha
  - wrangler@4.128.0
  - '@cloudflare/vitest-plugin@1.1.3'
