import { test, expect } from '@playwright/test'

test('station: mobile departure, controls, pause, full ride and return', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/api/auth/me', route => route.fulfill({ status: 401, json: { error: 'unauthorized' } }))
  await page.route('**/api/station/public', route => route.fulfill({ json: { global: { holderId: null, holderName: null, leg: 0, world: 'coast', seed: 'test' }, chronicles: [], rankings: [] } }))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'One baton. Endless horizons.' })).toBeVisible()
  await expect(page.locator('canvas')).toBeVisible()
  await page.screenshot({ path: '/tmp/nim-relay-production/station-mobile.png' })
  await page.getByRole('button', { name: 'rankings', exact: true }).click()
  await expect(page.getByText('The departure board is clear.')).toBeVisible()
  await page.getByRole('button', { name: 'Close panel' }).click()
  await page.getByRole('button', { name: 'Ride Sunbreak Coast' }).click()
  await page.getByRole('button', { name: 'Let’s ride' }).click()
  await expect(page.locator('.race-controls')).toBeVisible({ timeout: 8000 })
  await page.keyboard.down(' ')
  await page.keyboard.press('ArrowUp')
  await page.waitForTimeout(1600)
  await page.keyboard.up(' ')
  await page.screenshot({ path: '/tmp/nim-relay-production/race-mobile.png' })
  await page.keyboard.press('Escape')
  await expect(page.getByText('Take a breath.')).toBeVisible()
  await page.getByRole('button', { name: 'Keep riding' }).click()
  await page.keyboard.down(' ')
  await expect(page.getByRole('button', { name: 'Return to station' })).toBeVisible({ timeout: 100000 })
  await page.keyboard.up(' ')
  await expect(page.getByText('This ride could not be verified.')).toBeHidden()
  await page.screenshot({ path: '/tmp/nim-relay-production/results-mobile.png' })
  await page.getByRole('button', { name: 'Return to station' }).click()
  await expect(page.getByRole('heading', { name: 'One baton. Endless horizons.' })).toBeVisible()
  expect(errors).toEqual([])
})

test('all five worlds load with their own scene and no runtime errors', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/api/auth/me', route => route.fulfill({ status: 401, json: { error: 'unauthorized' } }))
  await page.route('**/api/station/public', route => route.fulfill({ json: { global: { holderId: null, holderName: null, leg: 0, world: 'coast', seed: 'test' }, chronicles: [], rankings: [] } }))
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.goto('/')
  for (const name of ['Sunbreak Coast', 'Cloudline Alps', 'Midnight Metro', 'Solar Frontier', 'Ocean Skyway']) {
    await page.getByRole('button', { name, exact: true }).click()
    await page.getByRole('button', { name: `Ride ${name}` }).click()
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible()
    await page.waitForTimeout(700)
    await page.screenshot({ path: `/tmp/nim-relay-production/world-${name.replaceAll(' ', '-')}.png` })
    await page.getByRole('button', { name: 'Back to station' }).click()
  }
  expect(errors).toEqual([])
})
