/**
 * Generated by scripts/assets/build-audio.mjs. Do not edit by hand: change the plan in
 * scripts/assets/audio/plan.mjs and rerun the build. Licences and processing notes for every
 * file are in apps/web/public/assets/manifest.json.
 */
import type { relayLeg } from '@nim-relay/game-engine'

export type TrackRole = 'race' | 'world' | 'station' | 'ceremony' | 'wind' | 'hover' | 'rail'

export type PitchClass = 'C' | 'C#' | 'D' | 'D#' | 'E' | 'F' | 'F#' | 'G' | 'G#' | 'A' | 'A#' | 'B'

export interface TrackMeta {
  readonly id: TrackId
  readonly url: string
  readonly role: TrackRole
  /** Tempo of the shipped file. Race tracks are stretched to the engine's 144 BPM pulse grid. */
  readonly bpm: number | null
  readonly bars: number | null
  /** The decoded file is exactly this long and loops end to start. Race tracks start on beat 0. */
  readonly loopSeconds: number
  /** Linear playback gain on top of the file's normalised loudness. */
  readonly gain: number
  /** Measured tonal centre. Synthesized layers only use its root and fifth. */
  readonly tonic: PitchClass | null
  /** Race tracks: the worlds that ride to this track. */
  readonly worlds: readonly relayLeg.World[]
  /** Race tracks: measured downbeat after time-stretching, relative to its nominal bar line. */
  readonly downbeatOffsetMs: number | null
  readonly bytes: number
}

export interface SoundMeta {
  readonly id: SoundId
  readonly url: string
  readonly seconds: number
  readonly channels: 1 | 2
  readonly bytes: number
}

export type TrackId =
  | 'race-neon'
  | 'race-highway'
  | 'world-space-city'
  | 'station-mirrorshade'
  | 'ceremony-mirrorshade'
  | 'wind'
  | 'hover'
  | 'rail'

export type SoundId =
  | 'gate-perfect'
  | 'gate-miss'
  | 'pulse-hit'
  | 'near-miss-a'
  | 'near-miss-b'
  | 'hit-a'
  | 'hit-b'
  | 'jump'
  | 'land'
  | 'clean-land'
  | 'slide'
  | 'rail-on'
  | 'rail-off'
  | 'boost'
  | 'fork-safe'
  | 'fork-risk'
  | 'risk-clear'
  | 'fall-whoosh'
  | 'fall-boom'
  | 'flow-max'
  | 'finish'
  | 'overtake'
  | 'overtaken'
  | 'approach'
  | 'finish-win'
  | 'finish-lose'
  | 'ui-tap'
  | 'ui-back'
  | 'ui-error'
  | 'wallet-open'
  | 'wallet-paused'
  | 'handoff-in-flight'
  | 'handoff-confirmed'
  | 'arrival'
  | 'incoming'
  | 'catch'
  | 'launch-whoosh'

export const TRACKS: Readonly<Record<TrackId, TrackMeta>> = {
  'race-neon': {
    id: 'race-neon',
    url: '/assets/audio/music/race-neon.m4a',
    role: 'race',
    bpm: 144,
    bars: 60,
    loopSeconds: 100,
    gain: 0.8,
    tonic: 'G',
    worlds: ['metro', 'solar'],
    downbeatOffsetMs: -8.68,
    bytes: 1666963,
  },
  'race-highway': {
    id: 'race-highway',
    url: '/assets/audio/music/race-highway.m4a',
    role: 'race',
    bpm: 144,
    bars: 52,
    loopSeconds: 86.66666666666667,
    gain: 0.8,
    tonic: 'A',
    worlds: ['coast', 'alpine', 'ocean'],
    downbeatOffsetMs: 11.88,
    bytes: 1453762,
  },
  'world-space-city': {
    id: 'world-space-city',
    url: '/assets/audio/music/world-space-city.m4a',
    role: 'world',
    bpm: 115,
    bars: 56,
    loopSeconds: 116.86954648526077,
    gain: 0.5,
    tonic: 'D#',
    worlds: [],
    downbeatOffsetMs: null,
    bytes: 1918145,
  },
  'station-mirrorshade': {
    id: 'station-mirrorshade',
    url: '/assets/audio/music/station-mirrorshade.m4a',
    role: 'station',
    bpm: 107,
    bars: 4,
    loopSeconds: 8.971972789115647,
    gain: 0.55,
    tonic: 'A',
    worlds: [],
    downbeatOffsetMs: null,
    bytes: 150142,
  },
  'ceremony-mirrorshade': {
    id: 'ceremony-mirrorshade',
    url: '/assets/audio/music/ceremony-mirrorshade.m4a',
    role: 'ceremony',
    bpm: 107,
    bars: 4,
    loopSeconds: 8.971972789115647,
    gain: 0.6,
    tonic: 'A',
    worlds: [],
    downbeatOffsetMs: null,
    bytes: 149651,
  },
  'wind': {
    id: 'wind',
    url: '/assets/audio/ambience/wind.m4a',
    role: 'wind',
    bpm: null,
    bars: null,
    loopSeconds: 5.959297052154195,
    gain: 0.9,
    tonic: null,
    worlds: [],
    downbeatOffsetMs: null,
    bytes: 73945,
  },
  'hover': {
    id: 'hover',
    url: '/assets/audio/ambience/hover.m4a',
    role: 'hover',
    bpm: null,
    bars: null,
    loopSeconds: 4,
    gain: 0.35,
    tonic: null,
    worlds: [],
    downbeatOffsetMs: null,
    bytes: 49981,
  },
  'rail': {
    id: 'rail',
    url: '/assets/audio/ambience/rail.m4a',
    role: 'rail',
    bpm: null,
    bars: null,
    loopSeconds: 5.237301587301587,
    gain: 0.6,
    tonic: null,
    worlds: [],
    downbeatOffsetMs: null,
    bytes: 65579,
  },
}

export const SOUNDS: Readonly<Record<SoundId, SoundMeta>> = {
  'gate-perfect': { id: 'gate-perfect', url: '/assets/audio/sfx/gate-perfect.m4a', seconds: 0.3628, channels: 1, bytes: 5749 },
  'gate-miss': { id: 'gate-miss', url: '/assets/audio/sfx/gate-miss.m4a', seconds: 0.4054, channels: 1, bytes: 6290 },
  'pulse-hit': { id: 'pulse-hit', url: '/assets/audio/sfx/pulse-hit.m4a', seconds: 0.267, channels: 1, bytes: 4308 },
  'near-miss-a': { id: 'near-miss-a', url: '/assets/audio/sfx/near-miss-a.m4a', seconds: 0.1102, channels: 1, bytes: 2031 },
  'near-miss-b': { id: 'near-miss-b', url: '/assets/audio/sfx/near-miss-b.m4a', seconds: 0.166, channels: 1, bytes: 2459 },
  'hit-a': { id: 'hit-a', url: '/assets/audio/sfx/hit-a.m4a', seconds: 0.6309, channels: 1, bytes: 6269 },
  'hit-b': { id: 'hit-b', url: '/assets/audio/sfx/hit-b.m4a', seconds: 0.4738, channels: 1, bytes: 5000 },
  'jump': { id: 'jump', url: '/assets/audio/sfx/jump.m4a', seconds: 0.3102, channels: 1, bytes: 3631 },
  'land': { id: 'land', url: '/assets/audio/sfx/land.m4a', seconds: 0.5413, channels: 1, bytes: 5387 },
  'clean-land': { id: 'clean-land', url: '/assets/audio/sfx/clean-land.m4a', seconds: 0.2898, channels: 1, bytes: 4824 },
  'slide': { id: 'slide', url: '/assets/audio/sfx/slide.m4a', seconds: 0.5751, channels: 1, bytes: 5891 },
  'rail-on': { id: 'rail-on', url: '/assets/audio/sfx/rail-on.m4a', seconds: 0.1648, channels: 1, bytes: 2450 },
  'rail-off': { id: 'rail-off', url: '/assets/audio/sfx/rail-off.m4a', seconds: 0.0778, channels: 1, bytes: 1870 },
  'boost': { id: 'boost', url: '/assets/audio/sfx/boost.m4a', seconds: 0.3417, channels: 1, bytes: 3917 },
  'fork-safe': { id: 'fork-safe', url: '/assets/audio/sfx/fork-safe.m4a', seconds: 0.611, channels: 1, bytes: 8659 },
  'fork-risk': { id: 'fork-risk', url: '/assets/audio/sfx/fork-risk.m4a', seconds: 0.4596, channels: 1, bytes: 6792 },
  'risk-clear': { id: 'risk-clear', url: '/assets/audio/sfx/risk-clear.m4a', seconds: 1.1016, channels: 1, bytes: 14642 },
  'fall-whoosh': { id: 'fall-whoosh', url: '/assets/audio/sfx/fall-whoosh.m4a', seconds: 0.9424, channels: 1, bytes: 8854 },
  'fall-boom': { id: 'fall-boom', url: '/assets/audio/sfx/fall-boom.m4a', seconds: 0.9936, channels: 1, bytes: 9255 },
  'flow-max': { id: 'flow-max', url: '/assets/audio/sfx/flow-max.m4a', seconds: 0.3045, channels: 1, bytes: 4801 },
  'finish': { id: 'finish', url: '/assets/audio/sfx/finish.m4a', seconds: 0.9438, channels: 1, bytes: 12546 },
  'overtake': { id: 'overtake', url: '/assets/audio/sfx/overtake.m4a', seconds: 0.3328, channels: 1, bytes: 5493 },
  'overtaken': { id: 'overtaken', url: '/assets/audio/sfx/overtaken.m4a', seconds: 0.4429, channels: 1, bytes: 6594 },
  'approach': { id: 'approach', url: '/assets/audio/sfx/approach.m4a', seconds: 0.6326, channels: 1, bytes: 8866 },
  'finish-win': { id: 'finish-win', url: '/assets/audio/sfx/finish-win.m4a', seconds: 5.2152, channels: 2, bytes: 85636 },
  'finish-lose': { id: 'finish-lose', url: '/assets/audio/sfx/finish-lose.m4a', seconds: 1.3753, channels: 1, bytes: 17876 },
  'ui-tap': { id: 'ui-tap', url: '/assets/audio/sfx/ui-tap.m4a', seconds: 0.0404, channels: 1, bytes: 1458 },
  'ui-back': { id: 'ui-back', url: '/assets/audio/sfx/ui-back.m4a', seconds: 0.0914, channels: 1, bytes: 1741 },
  'ui-error': { id: 'ui-error', url: '/assets/audio/sfx/ui-error.m4a', seconds: 0.2742, channels: 1, bytes: 3331 },
  'wallet-open': { id: 'wallet-open', url: '/assets/audio/sfx/wallet-open.m4a', seconds: 0.2546, channels: 1, bytes: 4242 },
  'wallet-paused': { id: 'wallet-paused', url: '/assets/audio/sfx/wallet-paused.m4a', seconds: 0.2584, channels: 1, bytes: 4280 },
  'handoff-in-flight': { id: 'handoff-in-flight', url: '/assets/audio/sfx/handoff-in-flight.m4a', seconds: 0.9044, channels: 1, bytes: 12152 },
  'handoff-confirmed': { id: 'handoff-confirmed', url: '/assets/audio/sfx/handoff-confirmed.m4a', seconds: 0.4896, channels: 1, bytes: 7232 },
  'arrival': { id: 'arrival', url: '/assets/audio/sfx/arrival.m4a', seconds: 0.6923, channels: 1, bytes: 9653 },
  'incoming': { id: 'incoming', url: '/assets/audio/sfx/incoming.m4a', seconds: 0.5339, channels: 1, bytes: 7737 },
  'catch': { id: 'catch', url: '/assets/audio/sfx/catch.m4a', seconds: 0.1617, channels: 1, bytes: 3161 },
  'launch-whoosh': { id: 'launch-whoosh', url: '/assets/audio/sfx/launch-whoosh.m4a', seconds: 0.5179, channels: 1, bytes: 5335 },
}
