import { stationRace } from '@nim-relay/game-engine';
import * as T from 'three';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';

export type World = 'coast' | 'alpine' | 'metro' | 'solar' | 'ocean';
export interface Cosmetics { suit?: string; helmet?: string; board?: string; trail?: string; crewColor?: string; handoffs?: number }
type RaceState = stationRace.State;
export interface VisualSnapshot { phase: string; state: RaceState; ghost: RaceState | null }
export interface VisualController { frame(now:number): unknown; getRenderSnapshot(): VisualSnapshot; getThrow?(): { angle: number; power: number } }
export interface RaceOptions { world?: World; cosmetics?: Cosmetics; onFrame?: (snapshot: VisualSnapshot) => void }
const cosmeticColors: Record<string,string>={solar:'#eee5d7',ice:'#a5c9df',midnight:'#343e64',visor:'#e6e8ee',halo:'#f5c969',vector:'#1c2c42',comet:'#b9884e',gold:'#ffbc4e',aurora:'#c7b5ee'};
function cosmeticColor(value:string|undefined,fallback:string){return value ? cosmeticColors[value]??(/^#[0-9a-f]{6}$/i.test(value)?value:fallback):fallback;}
const Q=65536;
const palettes: Record<World,{sky:number;fog:number;surface:number;building:number;accent:number;water:number}>={
 coast:{sky:0x8197b9,fog:0xa5bacb,surface:0x303b57,building:0xd1d6da,accent:0xffc26b,water:0x315d79},
 alpine:{sky:0x707eab,fog:0xa7b5ce,surface:0x39485f,building:0xdbe4ed,accent:0xffd89b,water:0x456879},
 metro:{sky:0x10172d,fog:0x243051,surface:0x242b43,building:0x293452,accent:0xf1b369,water:0x18273c},
 solar:{sky:0xc89a89,fog:0xd4a188,surface:0x6f5554,building:0xd6b095,accent:0xffdc83,water:0xa7704e},
 ocean:{sky:0x718ca9,fog:0x95aec0,surface:0x394e65,building:0xc3d4db,accent:0xffce75,water:0x234a65},
};
const cube=new T.BoxGeometry(1,1,1);
const cylinder=new T.CylinderGeometry(1,1,1,12);
const sphere=new T.SphereGeometry(1,16,10);
const gold=0xf5a623;
function mat(color:number,metalness=.2,emissive=0){return new T.MeshStandardMaterial({color,roughness:.55,metalness,emissive,emissiveIntensity:.8});}
function mesh(parent:T.Object3D,geometry:T.BufferGeometry,material:T.Material,x:number,y:number,z:number,sx:number,sy:number,sz:number){const m=new T.Mesh(geometry,material);m.position.set(x,y,z);m.scale.set(sx,sy,sz);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
function block(parent:T.Object3D,material:T.Material,x:number,y:number,z:number,sx:number,sy:number,sz:number){return mesh(parent,cube,material,x,y,z,sx,sy,sz);}
function setup(host:HTMLElement,world:World){
 const p=palettes[world],scene=new T.Scene();scene.background=new T.Color(p.sky);scene.fog=new T.FogExp2(p.fog,.007);
 const camera=new T.PerspectiveCamera(48,1,.1,900);const renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;host.appendChild(renderer.domElement);renderer.domElement.style.cssText='display:block;width:100%;height:100%;touch-action:none';
 scene.add(new T.HemisphereLight(0xc6d9ff,0x4b3a50,2.3));const sun=new T.DirectionalLight(0xffdeb0,3.4);sun.position.set(-25,45,25);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-40;sun.shadow.camera.right=40;sun.shadow.camera.top=40;sun.shadow.camera.bottom=-40;scene.add(sun);const fill=new T.DirectionalLight(0xa9bbff,1.2);fill.position.set(15,8,-30);scene.add(fill);
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/Math.max(h,1);camera.updateProjectionMatrix();};const observer=new ResizeObserver(resize);observer.observe(host);resize();
 let alive=true,raf=0,last=0,slow=0,frames=0;const animate=(fn:(time:number,delta:number)=>void)=>{const draw=(now:number)=>{if(!alive)return;const dt=Math.min(.05,(now-last)/1000||.016);last=now;fn(now/1000,dt);renderer.render(scene,camera);frames++;if(dt>.028)slow++;if(frames===180){if(slow>50){renderer.setPixelRatio(Math.max(1,renderer.getPixelRatio()-.25));renderer.shadowMap.enabled=false;}frames=0;slow=0;}raf=requestAnimationFrame(draw);};raf=requestAnimationFrame(draw);};
 const dispose=()=>{alive=false;cancelAnimationFrame(raf);observer.disconnect();scene.traverse(o=>{if(o instanceof T.Mesh){if(o.geometry!==cube&&o.geometry!==cylinder&&o.geometry!==sphere)o.geometry.dispose();for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});renderer.dispose();renderer.domElement.remove();};return{scene,camera,renderer,animate,dispose,p,isAlive:()=>alive};
}
interface Courier { group:T.Group; pose:(name:string,dt:number)=>void }
function courier(parent:T.Object3D,cosmetics:Cosmetics={},ghost=false):Courier{
 const group=new T.Group();parent.add(group);let mixer:T.AnimationMixer|undefined,actions=new Map<string,T.AnimationAction>(),current='';
 void new GLTFLoader().loadAsync('/assets/courier.glb').then(gltf=>{gltf.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=!ghost;o.receiveShadow=!ghost;const source=o.material as T.MeshStandardMaterial;const m=source.clone();if(ghost){m.transparent=true;m.opacity=.28;m.depthWrite=false;m.color.set(0xc4ddff);m.emissive.set(0x6e8aad);m.emissiveIntensity=.6;}else {if(source.name==='suit'&&cosmetics.suit)m.color.set(cosmeticColor(cosmetics.suit,'#eee5d7'));if(o.name==='Helmet'&&cosmetics.helmet)m.color.set(cosmeticColor(cosmetics.helmet,'#e6e8ee'));if(o.name==='BoardDeck'&&cosmetics.board)m.color.set(cosmeticColor(cosmetics.board,'#1c2c42'));if(source.name==='gold'&&cosmetics.crewColor)m.color.set(cosmetics.crewColor);}o.material=m;}});group.add(gltf.scene);mixer=new T.AnimationMixer(gltf.scene);actions=new Map(gltf.animations.map(clip=>[clip.name,mixer!.clipAction(clip)]));actions.get('idle')?.play();}).catch(error=>console.error('Courier asset could not load',error));
 return{group,pose(name,dt){if(name!==current){actions.get(current)?.fadeOut(.16);actions.get(name)?.reset().fadeIn(.16).play();current=name;}mixer?.update(dt);}};
}
function baton(parent:T.Object3D,handoffs=0){const group=new T.Group();parent.add(group);mesh(group,new T.CylinderGeometry(.25,.25,2.1,6),mat(gold,.8,0xb65908),0,0,0,1,1,1);const count=Math.min(14,Math.floor(Math.sqrt(Math.max(0,handoffs))));for(let i=0;i<count;i++){const ring=new T.Mesh(new T.TorusGeometry(.3,.027,6,6),mat(0xffe6a6,.7,0xe09b32));ring.rotation.x=Math.PI/2;ring.position.y=-.85+i*1.7/Math.max(1,count-1);group.add(ring);}const light=new T.PointLight(0xffb83e,12,12);group.add(light);return group;}
function skyline(parent:T.Object3D,world:World,station=false){const p=palettes[world],material=mat(p.building),dark=mat(p.surface),light=mat(p.accent,.3,p.accent);const objects=new T.InstancedMesh(cube,material,180);const transform=new T.Object3D();for(let i=0;i<180;i++){const side=i%2?1:-1;const z=station?Math.sin(i*2.4)*110-20:30-i*4;const x=side*(22+(i*17%97));const h=8+(i*19%61);transform.position.set(x,h/2-9,z);transform.scale.set(4+i%6,h,4+i%8);transform.rotation.y=i*.6;transform.updateMatrix();objects.setMatrixAt(i,transform.matrix);}objects.castShadow=true;parent.add(objects);
 for(let i=0;i<22;i++){const side=i%2?1:-1;const z=-i*24;const x=side*(17+i%3*9);if(world==='alpine'){mesh(parent,new T.ConeGeometry(1,1,5),mat(i%2?0xd5e0e9:0x778999),x*2,7,z,20,45+i%5*9,24);for(let j=0;j<4;j++)mesh(parent,new T.ConeGeometry(1,1,7),mat(0x344d53),x+j*3,-1,z+j*2,2,8,2);}else if(world==='solar'){const panel=block(parent,dark,x,3,z,12,.4,8);panel.rotation.z=side*.3;block(parent,material,x,0,z,.5,6,.5);mesh(parent,new T.ConeGeometry(1,1,5),mat(0xba8666),x*3,-8,z,25,12,20);}else if(world==='ocean'){mesh(parent,cylinder,material,x,-2,z,8,6,8);block(parent,dark,x,5,z,8,9,5);block(parent,light,x,10,z,8,.15,5);}else{block(parent,dark,x,4,z,8,2,5);block(parent,light,x,5.1,z,8,.1,5);if(world==='coast'){const arch=new T.Mesh(new T.TorusGeometry(7,.35,6,30,Math.PI),material);arch.position.set(x,6,z);parent.add(arch);}}}
 const water=block(parent,mat(p.water,.6),0,-10,-180,900,.5,1000);return water;
}
function label(text:string){const canvas=document.createElement('canvas');canvas.width=512;canvas.height=128;const ctx=canvas.getContext('2d');if(ctx){ctx.fillStyle='rgba(12,20,39,.84)';ctx.roundRect(0,0,512,128,22);ctx.fill();ctx.font='600 42px system-ui';ctx.fillStyle='#f7e8cd';ctx.textAlign='center';ctx.fillText(text,256,80);}const texture=new T.CanvasTexture(canvas);const sprite=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:false}));sprite.scale.set(5,1.25,1);return sprite;}
export function mountStation(host:HTMLElement,onSelect:(destination:string)=>void,cosmetics:Cosmetics={}){
 const r=setup(host,'coast');r.camera.position.set(21,20,29);r.camera.lookAt(0,3,0);skyline(r.scene,'coast',true);const floor=mat(0x7e8b9e,.35),trim=mat(gold,.6),dark=mat(0x29344a);mesh(r.scene,cylinder,floor,0,-1.2,0,17,1.4,17);mesh(r.scene,cylinder,dark,0,-2.1,0,17.6,.4,17.6);
 for(let i=0;i<28;i++){const a=i/28*Math.PI*2;block(r.scene,trim,Math.cos(a)*16,-.42,Math.sin(a)*16,.13,.06,.8).rotation.y=-a;}
 const center=new T.Group();r.scene.add(center);mesh(center,cylinder,dark,0,0,0,3.2,1,3.2);mesh(center,cylinder,trim,0,.6,0,2.8,.12,2.8);const core=baton(center,cosmetics.handoffs);core.position.y=3.3;core.scale.setScalar(1.7);const arch=new T.Mesh(new T.TorusGeometry(4,.13,8,64,Math.PI*1.5),trim);arch.position.y=3;arch.rotation.z=-Math.PI/4;center.add(arch);
 const player=courier(r.scene,cosmetics);player.group.position.set(3.7,.2,6);player.group.scale.setScalar(1.7);player.group.rotation.y=-.6;
 const places=[['quick','Departure',-8,5],['global','Global Relay',-7,-7],['crew','Crew docks',7,-8],['daily','Daily Circuit',10,1],['inbox','Arrivals',0,11],['customize','Workshop',-12,-1],['gallery','Baton archive',1,-12],['rival','Rivals',12,8],['rankings','Rankings',-11,10],['profile','Courier',6,11],['chronicles','Chronicles',-1,-7]] as const;
 const targets:T.Object3D[]=[];for(const [id,title,x,z] of places){const building=new T.Group();building.position.set(x,0,z);r.scene.add(building);mesh(building,cylinder,dark,0,0,0,2.1,.5,2.1);block(building,floor,-1.45,1.1,0,.28,2.5,1.7);block(building,floor,1.45,1.1,0,.28,2.5,1.7);block(building,trim,0,2.4,0,3.2,.17,1.8);const sign=label(title);sign.position.y=3.4;building.add(sign);building.userData.destination=id;building.traverse(o=>{o.userData.destination=id;targets.push(o);});}
 const shuttles=Array.from({length:4},(_,i)=>{const g=new T.Group();r.scene.add(g);mesh(g,sphere,mat(0xd3dae4),0,0,0,1.6,.5,3.4);block(g,dark,0,.3,-1,1.5,.4,1.2);block(g,trim,0,-.3,2.4,1.2,.1,.5);g.position.set(i*15-25,4+i*3,-20);return g;});
 const visitors=Array.from({length:3},(_,i)=>{const c=courier(r.scene,{suit:['#d3a16f','#7286a7','#c4cace'][i]!});c.group.scale.setScalar(.9);return c;});const ray=new T.Raycaster(),pointer=new T.Vector2();const click=(e:PointerEvent)=>{const b=host.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,r.camera);const hit=ray.intersectObjects(targets,false)[0];if(hit&&typeof hit.object.userData.destination==='string')onSelect(hit.object.userData.destination);};r.renderer.domElement.addEventListener('pointerup',click);
 r.animate((t,dt)=>{core.rotation.y=t*.35;core.position.y=3.3+Math.sin(t*1.3)*.15;player.pose('idle',dt);shuttles.forEach((s,i)=>{s.position.x=((t*(2+i*.3)+i*25)%130)-65;s.position.y=8+i*2+Math.sin(t+i)*.3;});visitors.forEach((c,i)=>{const a=t*.10+i*2.1;c.group.position.set(Math.cos(a)*10,.1,Math.sin(a)*10);c.group.rotation.y=-a;c.pose('idle',dt);});});return()=>{r.renderer.domElement.removeEventListener('pointerup',click);r.dispose();};
}
function worldLandmarks(parent:T.Object3D,world:World){
 const animated:T.Group[]=[];const shell=mat(palettes[world].building,.5),structure=mat(palettes[world].surface,.6),glow=mat(gold,.5,0xbd720c);
 for(let i=0;i<5;i++){const z=-50-i*135,side=i%2?1:-1,x=side*23;
  if(world==='ocean'){block(parent,shell,x,3,z,1.2,30,1.2);const rotor=new T.Group();rotor.position.set(x,18,z);parent.add(rotor);mesh(rotor,sphere,structure,0,0,0,1,1,1);for(let b=0;b<3;b++){const arm=new T.Group();arm.rotation.z=b*Math.PI*2/3;rotor.add(arm);block(arm,shell,0,5,0,.8,10,.25);}animated.push(rotor);}
  else if(world==='alpine'){block(parent,structure,-18,12,z,.5,24,.5);block(parent,structure,18,12,z,.5,24,.5);block(parent,structure,0,23,z,40,.12,.12);const car=new T.Group();car.position.set(x/2,21,z);parent.add(car);block(car,glow,0,-1,0,2.8,2.5,2);block(car,structure,0,-.5,-1.03,2.4,1,.08);car.userData.sway=true;animated.push(car);}
  else if(world==='solar'){const dish=new T.Group();dish.position.set(x,10,z);dish.rotation.x=.55;parent.add(dish);mesh(dish,new T.CylinderGeometry(8,2,.8,6),shell,0,0,0,1,1,1);mesh(dish,cylinder,glow,0,3,0,.14,6,.14);block(parent,structure,x,0,z,1,18,1);dish.userData.sway=true;animated.push(dish);}
  else if(world==='metro'){block(parent,structure,0,18,z,52,1,4);const train=new T.Group();train.position.set(x,20,z);parent.add(train);for(let c=0;c<3;c++){block(train,shell,c*8,0,0,7.7,2.4,2.5);block(train,glow,c*8,.3,-1.26,6.4,.5,.06);}train.userData.transit=true;animated.push(train);}
  else{const sail=new T.Mesh(new T.ConeGeometry(10,32,3,1,true),shell);sail.position.set(x,10,z);sail.rotation.y=i*.7;parent.add(sail);block(parent,structure,x,0,z,.5,30,.5);}
 }return(time:number)=>animated.forEach((object,i)=>{if(object.userData.transit)object.position.x=((time*7+i*23)%100)-50;else if(object.userData.sway)object.rotation.z=Math.sin(time*.35+i)*.08;else object.rotation.z=time*.25+i;});
}
export function mountRace(host:HTMLElement,controller:VisualController,options:RaceOptions={}){
 const world=options.world??'coast',r=setup(host,world);r.camera.fov=61;r.camera.updateProjectionMatrix();r.camera.position.set(0,4.4,9);const course=new T.Group();r.scene.add(course);course.scale.set(1,1,8);const env=new T.Group();r.scene.add(env);skyline(env,world);const animateLandmarks=worldLandmarks(env,world);const player=courier(r.scene,options.cosmetics),ghost=courier(r.scene,{},true);const surface=mat(r.p.surface,.35),edge=mat(0xb7c6d8,.5),positive=mat(gold,.6,0xa85505),danger=mat(0xed4a3d,.25,0xa5221a);let built=false;const movers:{object:T.Mesh;hazard:RaceState['track']['hazards'][number]}[]=[];const beats:T.Mesh[]=[];let previousX=0,previousY=0,previousStumble=0,launchStart=0;
 const launchBaton=baton(r.scene,options.cosmetics?.handoffs);launchBaton.visible=false;const burstCount=120,positions=new Float32Array(burstCount*3);const particles=new T.BufferGeometry();particles.setAttribute('position',new T.BufferAttribute(positions,3));const points=new T.Points(particles,new T.PointsMaterial({color:gold,size:.13,transparent:true,opacity:.8,depthWrite:false}));r.scene.add(points);let burst=0;
 const trails=new T.Group();r.scene.add(trails);const trailMaterial=new T.MeshBasicMaterial({color:cosmeticColor(options.cosmetics?.trail,'#ffbc4e'),transparent:true,opacity:.5,depthWrite:false});for(const x of [-.28,.28])block(trails,trailMaterial,x,.1,2,.1,.06,4);
 const streakGeometry=new T.BufferGeometry(),streakPositions=new Float32Array(70*6);for(let i=0;i<70;i++){const x=((i*17)%31)-15,y=(i*7)%13,z=-((i*23)%100);streakPositions.set([x,y,z,x,y,z+2],i*6);}streakGeometry.setAttribute('position',new T.BufferAttribute(streakPositions,3));const streaks=new T.LineSegments(streakGeometry,new T.LineBasicMaterial({color:0xffe3b0,transparent:true,opacity:.25}));r.scene.add(streaks);
 function build(state:RaceState){const track=state.track;const length=track.finishDist/Q;const ground=(dist:number)=>{return stationRace.groundAt(track,Math.round(dist*Q))/Q;};
 // Independent slabs stop at authored gaps, leaving a genuinely open route.
 for(let d=0;d<length;d+=.5){if(track.gaps.some(g=>d>=g.from/Q&&d<g.to/Q))continue;const y=ground(d);block(course,surface,0,y-.35,-d,12,.6,.5);for(const x of [-6.1,6.1]){block(course,edge,x,y,-d,.15,.15,.48);if(Math.floor(d/4)%4===0)block(course,positive,x,y+.03,-d,.20,.12,1.2);}if(Math.floor(d/4)%8===0){block(course,edge,0,y-.95,-d,13,.6,.6);for(const x of [-4,4])block(course,surface,x,y-8,-d,.8,14,.8);}}
 for(const gate of track.gates){const d=gate.dist/Q,y=ground(d);const g=new T.Group();g.position.set(gate.x/Q*6,y,-d);course.add(g);const half=gate.half/Q*6;for(const x of [-half,half])block(g,positive,x,1.3,0,.18,2.6,.3);const top=block(g,positive,0,2.7,0,half*2+.2,.2,.3);if(gate.kind==='beat')beats.push(top);block(g,positive,0,.025,0,half*2,.04,1);}
 for(const h of track.hazards){const y=ground(h.dist/Q);const beam=h.kind==='beam';const object=block(course,danger,h.x/Q*6,y+(beam?1.6:.5),-h.dist/Q,h.half/Q*12,beam?.55:1,.7);if(h.kind==='moving')movers.push({object,hazard:h});for(const x of [-h.half/Q,h.half/Q])block(object,edge,x/(h.half/Q*12),0,0,.04,1.1,1.1);}
 for(const z of track.boostZones){const d=(z.from+z.to)/Q/2;block(course,positive,(z.x??0)/Q*6,ground(d)+.025,-d,(z.half??Q)/Q*12,.045,(z.to-z.from)/Q);}
 for(const rail of track.rails){const d=(rail.from+rail.to)/Q/2;block(course,positive,(rail.x??0)/Q*6,ground(d)+.55,-d,.18,.18,(rail.to-rail.from)/Q);}
 for(const ramp of track.ramps){const d=(ramp.from+ramp.to)/Q/2,len=(ramp.to-ramp.from)/Q;const wedge=block(course,edge,(ramp.x??0)/Q*6,ground(d)+.35,-d,(ramp.half??2*Q)/Q*12,.3,len);wedge.rotation.x=.12;}
 // Authored bridges and collector towers punctuate the route.
 for(let d=12;d<length;d+=22){const y=ground(d);for(const side of [-1,1]){block(course,edge,side*10,y+9,-d,1.6,20,2);block(course,surface,side*10,y+17,-d,5,4,6);}block(course,edge,0,y+14,-d,22,.7,2);for(let k=0;k<9;k++)block(course,positive,k*2.4-9.6,y+13.5,-d,.3,.15,2);}
 const end=length;block(course,positive,0,ground(end)+.03,-end,12,.12,10);for(const x of [-7,7])block(course,edge,x,ground(end)+6,-end,1,12,2);block(course,positive,0,ground(end)+12,-end,15,.6,2);built=true;}
 r.animate((time,dt)=>{animateLandmarks(time);controller.frame(time*1000);const snapshot=controller.getRenderSnapshot(),s=snapshot.state;if(!built)build(s);options.onFrame?.(snapshot);const dist=s.dist/Q*8,x=s.x/Q*6,y=(s.y+s.groundHeight)/Q;course.position.z=dist;env.position.z=(dist%160);const heat=Math.min(1,s.heat/Q);player.group.position.set(x,y+.12,0);player.group.rotation.z=T.MathUtils.lerp(player.group.rotation.z,-(x-previousX)*2,.15);player.group.rotation.x=T.MathUtils.lerp(player.group.rotation.x,s.boosting?-.2:0,.1);
 const pose=snapshot.phase==='results'?'victory':snapshot.phase==='handoff'?'baton-handoff':s.stumbleTicks?'stumble':s.duckTicks?'duck-drift':y>previousY+.05?'jump':y<previousY-.06?'land':s.boosting?'boost':x<previousX-.025?'bank-left':x>previousX+.025?'bank-right':'idle';player.pose(pose,dt);ghost.group.visible=snapshot.ghost!==null;if(snapshot.ghost){const g=snapshot.ghost;ghost.group.position.set(g.x/Q*6,(g.y+g.groundHeight)/Q+.12,(s.dist-g.dist)/Q*8);ghost.pose(g.boosting?'boost':'idle',dt);}
 for(const {object,hazard} of movers){object.position.x=stationRace.hazardX(hazard,s.tick)/Q*6;}
 const beat=(s.tick%Math.max(1,s.track.beatPeriod))/Math.max(1,s.track.beatPeriod);for(const item of beats)item.scale.y=.15+(1-beat)*.35;trails.position.copy(player.group.position);trails.scale.z=s.boosting?2+heat*2:.35;trailMaterial.color.set(s.overheatTicks?0xff493c:cosmeticColor(options.cosmetics?.trail,'#ffbc4e'));streaks.visible=Boolean(s.boosting);streaks.position.z=(time*40)%10;
 if(s.stumbleTicks>previousStumble)burst=1;burst=Math.max(0,burst-dt*1.5);points.visible=burst>0;if(burst>0){for(let i=0;i<burstCount;i++){const spread=(1-burst)*4;positions[i*3]=x+Math.sin(i*8.2)*spread;positions[i*3+1]=y+.3+Math.cos(i*3.7)*spread*.4;positions[i*3+2]=Math.sin(i*2.7)*spread;}particles.attributes.position!.needsUpdate=true;}
 const fov=61+(s.boosting?9:0)+heat*3;r.camera.fov=T.MathUtils.lerp(r.camera.fov,fov,.04);r.camera.updateProjectionMatrix();r.camera.position.x=T.MathUtils.lerp(r.camera.position.x,x*.45,.07);r.camera.position.y=T.MathUtils.lerp(r.camera.position.y,y+3.5,.06);r.camera.position.z=8.5;r.camera.lookAt(x*.7,y+1.2,-9);r.camera.rotation.z=player.group.rotation.z*.16;
 if(snapshot.phase==='handoff'){r.camera.position.set(x+3,y+2.5,4);r.camera.lookAt(x,y+1,0);}if(snapshot.phase==='launch'){if(!launchStart)launchStart=time;const t=time-launchStart;launchBaton.visible=true;launchBaton.position.set(x,y+1.3+Math.sin((controller.getThrow?.().angle??45)*Math.PI/180)*t*(controller.getThrow?.().power??75)/10,-t*t*(controller.getThrow?.().power??75)/6);launchBaton.rotation.z=t*3;r.camera.position.set(x+3+t*3,y+3+t*4,7+t*7);r.camera.lookAt(launchBaton.position);}previousX=x;previousY=y;previousStumble=s.stumbleTicks;
 });return r.dispose;
}
