import type { CanonicalGhost, HandoffIntent, RaceMode, StationWorld } from './station'
export type RelayNetwork = 'TestAlbatross' | 'MainAlbatross'
export interface NetworkRunner { id: string; handle: string; name: string; wallet: string; country: string | null; countrySource: 'network_observed' | null }
export interface BatonHandoff { id: string; batonId: string; leg: number; from: NetworkRunner; to: NetworkRunner; value: number; txHash: string; network: RelayNetwork; at: number; runId: string; resultHash: string; qualified: boolean; confirmations: number; blockNumber: number }
export interface NetworkBaton { route?: { countryCode: string | null }[]; id: string; code: string; title: string; mode: Exclude<RaceMode, 'daily'>; network: RelayNetwork; value: number; origin: NetworkRunner; holder: NetworkRunner; createdAt: number; updatedAt: number; status: 'active' | 'completed' | 'stranded'; handoffCount: number; world: StationWorld; previousRunId: string | null; crewId: string | null; rivalId: string | null; recipientId: string | null; expiresAt: number; lineage: { countries: string[]; runners: number; ghostWins: number }; quick: { players: string[]; bestOf: 3 | 5; scores: Record<string, number>; rounds: number; winnerId: string | null; rematchOf: string | null } | null }
export interface NetworkHandoffIntent extends HandoffIntent { batonId: string; createdAt: number; expiresAt: number; attemptedAt: number | null; state: 'prepared' | 'attempting' | 'submitted' | 'verified' | 'cancelled' | 'expired'; failure: string | null }
export interface NetworkNotification { id: string; type: 'incoming_baton' | 'your_turn' | 'ghost_beaten' | 'rematch' | 'crew_streak_risk' | 'rival_update' | 'daily_active'; title: string; body: string; batonId: string | null; runId: string | null; createdAt: number; readAt: number | null }
export interface NetworkCrew { id: string; code: string; name: string; members: NetworkRunner[]; batonIds: string[]; streak: number; bestStreak: number; todayHandoffs: number; contributions: Record<string, number>; deadline: number }
export interface NetworkRival { id: string; title: string; batonIds: [string, string]; target: number; scores: [number, number]; winnerId: string | null; createdAt: number; endsAt: number }
export interface NetworkInvite { id: string; token: string; batonId: string; from: NetworkRunner; recipientId: string | null; createdAt: number; expiresAt: number; claimedBy: string | null; url: string }
export interface NetworkDaily { date: string; world: StationWorld; seed: string; officialRunId: string | null; leaderboard: { player: NetworkRunner; runId: string; score: number; timeMs: number }[] }
export interface NetworkMetrics { linkedWallets: number; transactingWallets: number; qualifiedHandoffs: number; mainnetHandoffs: number; testnetHandoffs: number; invites: number; inviteConversions: number; returningWallets: number; quickRematches: number; crewActiveDays: number; dailyAttempts: number; foregroundSeconds: number; controlledEvidence: { handoffs: number; wallets: number }; definitions: string[] }
export interface NetworkSnapshot { network: RelayNetwork; batons: NetworkBaton[]; crews: NetworkCrew[]; rivals: NetworkRival[]; daily: NetworkDaily; metrics: NetworkMetrics; playerId: string | null; runners: NetworkRunner[]; inbox: NetworkNotification[]; invites: NetworkInvite[]; pendingHandoff: NetworkHandoffIntent | null; countryConsent: boolean }
export interface BatonDetail { baton: NetworkBaton; handoffs: BatonHandoff[]; ghost: CanonicalGhost | null; pendingHandoff: NetworkHandoffIntent | null; notableRuns: { runId: string; name: string; score: number; resultHash: string }[] }
export interface NetworkConfirmation { status: 'pending' | 'rejected' | 'verified'; reason?: string; intent?: NetworkHandoffIntent; baton?: NetworkBaton }
