import { z } from 'zod'
import { createClient } from '@supabase/supabase-js'
import { deriveCommitment, encodeTxData, paymentAddress, verifyHandoffTransaction, NimiqRpcClient } from '@nim-relay/relay-protocol'
import type { NetworkBaton, NetworkRunner, BatonHandoff, NetworkSnapshot, NetworkHandoffIntent, NetworkInvite, NetworkNotification, NetworkRival, BatonDetail, IssuedRace, CanonicalGhost, NetworkMetrics } from '@nim-relay/shared'
import type { Env } from '../env'
import { ApiError, mac, signedFields, type State, type Profile, type Run } from './room'
interface Member { consent: boolean; country: string | null; firstSeen: number; lastSeen: number; days: string[]; foreground: number; lastHeartbeat: number }
interface NetworkState { version: number; batons: Record<string, NetworkBaton>; handoffs: BatonHandoff[]; intents: Record<string, NetworkHandoffIntent>; notifications: Record<string, NetworkNotification[]>; invites: Record<string, NetworkInvite>; rivals: NetworkRival[]; members: Record<string, Member>; daily: Record<string, Record<string, { runId: string; score: number; timeMs: number }>>; dailyIssues: Record<string, string>; crewDays: Record<string, Record<string, number>>; rematches: number; dirty: boolean }
const fresh = (): NetworkState => ({ version: 1, batons: {}, handoffs: [], intents: {}, notifications: {}, invites: {}, rivals: [], members: {}, daily: {}, dailyIssues: {}, crewDays: {}, rematches: 0, dirty: false })
const day = () => new Date().toISOString().slice(0, 10)
const worlds = ['coast','alpine','metro','solar','ocean'] as const
const shortCode = () => crypto.randomUUID().replaceAll('-', '').slice(0, 10).toUpperCase()
async function tokenHash(token: string) { return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256', new TextEncoder().encode(token))), byte => byte.toString(16).padStart(2, '0')).join('') }
const idBody = z.object({ id: z.string().uuid() })
export class RelayNetworkService {
  readonly key: string
  private constructor(private storage: DurableObjectStorage, private env: Env, private product: State, readonly state: NetworkState) { this.key = `network:${env.NIMIQ_NETWORK}` }
  static async load(storage: DurableObjectStorage, env: Env, product: State) {
    const key = `network:${env.NIMIQ_NETWORK}`
    const stored = await storage.get<NetworkState | { chunks: number }>(key)
    if (!stored || !('chunks' in stored)) return new RelayNetworkService(storage, env, product, stored ?? fresh())
    const keys = Array.from({ length: stored.chunks }, (_, index) => `${key}:chunk:${index}`)
    const chunks = await storage.get<string>(keys)
    const serialized = keys.map(key => { const value = chunks.get(key); if (value === undefined) throw new Error('Relay archive segment missing'); return value }).join('')
    return new RelayNetworkService(storage, env, product, JSON.parse(serialized) as NetworkState)
  }
  async writeTo(storage: DurableObjectStorage | DurableObjectTransaction) {
    const serialized = JSON.stringify(this.state)
    const values: Record<string, unknown> = {}
    let chunks = 0
    // Keep each UTF-8 value below the Durable Object per-value limit.
    for (let offset = 0; offset < serialized.length; offset += 24000) values[`${this.key}:chunk:${chunks++}`] = serialized.slice(offset, offset + 24000)
    values[this.key] = { chunks }
    await storage.put(values)
  }
  private runner(profile: Profile): NetworkRunner { const member = this.state.members[profile.id]; return { id: profile.id, name: profile.name, handle: profile.handle, wallet: paymentAddress(profile.wallet), country: member?.consent ? member.country : null, countrySource: member?.consent && member.country ? 'network_observed' : null } }
  private other(value: string, profile: Profile): Profile { const other = Object.values(this.product.players).find(p => p.id === value || p.handle.toLowerCase() === value.trim().replace(/^@/, '').toLowerCase()); if (!other) throw new ApiError('courier_not_found',404); if (paymentAddress(other.wallet) === paymentAddress(profile.wallet)) throw new ApiError('choose_another_courier'); return other }
  private baton(value: string): NetworkBaton { const baton = this.state.batons[value] ?? Object.values(this.state.batons).find(b => b.code === value); if (!baton) throw new ApiError('journey_not_found',404); return baton }
  private holder(baton: NetworkBaton, profile: Profile) { if (baton.holder.id !== profile.id) throw new ApiError('only_current_holder_can_pass',403); if (baton.status === 'completed') throw new ApiError('journey_completed',409) }
  private notify(playerId: string, type: NetworkNotification['type'], title: string, body: string, batonId: string | null, runId: string | null = null) { const list = this.state.notifications[playerId] ??= []; list.unshift({ id: crypto.randomUUID(), type, title, body, batonId, runId, createdAt: Date.now(), readAt: null }); this.state.notifications[playerId] = list.slice(0,100) }
  private async ghost(runId: string | null): Promise<CanonicalGhost | null> { if (!runId) return null; const run = await this.storage.get<Run>(`run:${runId}`); if (!run || !run.result.completed) return null; return { runId, name: this.product.players[run.issued.playerId]?.name ?? 'Courier', config: run.issued.config, inputTrace: run.inputTrace, result: run.result, verified: true } }
  private pending(batonId: string) { return Object.values(this.state.intents).find(i => i.batonId === batonId && ['prepared','attempting','submitted'].includes(i.state)) ?? null }
  async detail(baton: NetworkBaton, profile?: Profile | null): Promise<BatonDetail> { const handoffs = this.state.handoffs.filter(h => h.batonId === baton.id); return { baton, handoffs, ghost: await this.ghost(baton.previousRunId), pendingHandoff: profile?.id === baton.holder.id ? this.pending(baton.id) : null, notableRuns: await Promise.all(handoffs.slice(-20).map(async h => ({ runId:h.runId, name:h.from.name, score:(await this.storage.get<Run>(`run:${h.runId}`))?.result.score??0, resultHash:h.resultHash }))) } }
  private create(profile: Profile, input: { mode: NetworkBaton['mode']; title: string; recipient?: string | undefined; bestOf?: 3|5 | undefined; crewId?: string | undefined }, rematchOf: string | null = null): NetworkBaton {
    if (Object.values(this.state.batons).filter(b => b.origin.id === profile.id && b.status === 'active').length >= 10) throw new ApiError('finish_an_active_journey_first',429)
    const other = input.recipient ? this.other(input.recipient,profile) : null
    if (input.mode === 'quick' && !other) throw new ApiError('choose_your_opponent')
    if (input.mode === 'crew' && (!profile.crewId || input.crewId && input.crewId !== profile.crewId)) throw new ApiError('join_a_crew_first')
    const runner = this.runner(profile), now = Date.now(), id = crypto.randomUUID()
    const baton: NetworkBaton = { id, code:shortCode(), title:input.title, mode:input.mode, network:this.env.NIMIQ_NETWORK, value:100000, origin:runner, holder:runner, createdAt:now, updatedAt:now, status:'active', handoffCount:0, world:worlds[Object.keys(this.state.batons).length%5]!, previousRunId:null, crewId:input.mode==='crew'?profile.crewId:null, rivalId:null, recipientId:other?.id??null, expiresAt:now+86400000, lineage:{countries:[],runners:1,ghostWins:0}, quick:input.mode==='quick'&&other?{players:[profile.id,other.id],bestOf:input.bestOf??3,scores:{[profile.id]:0,[other.id]:0},rounds:0,winnerId:null,rematchOf}:null }
    this.state.batons[id]=baton; if(other) this.notify(other.id,rematchOf?'rematch':'your_turn',`${profile.name} invited you`,`${baton.title} is ready. Accept the journey before the first pass.`,id)
    return baton
  }
  private daily(profile: Profile | null): NetworkSnapshot['daily'] { const date=day(), entries=this.state.daily[date]??{};return {date,world:worlds[Math.floor(Date.now()/86400000)%5]!,seed:`daily-${date}-v4`,officialRunId:profile?this.state.dailyIssues[`${date}:${profile.id}`]??null:null,leaderboard:Object.entries(entries).map(([id,e])=>({player:this.runner(this.product.players[id]!),...e})).sort((a,b)=>b.score-a.score).slice(0,100)} }
  private metrics(): NetworkMetrics { const hands=this.state.handoffs.filter(h=>h.qualified), wallets=new Set(hands.flatMap(h=>[h.from.wallet,h.to.wallet])); const test=this.env.NIMIQ_NETWORK==='TestAlbatross';return {linkedWallets:new Set(Object.keys(this.state.members).map(id=>this.product.players[id]?.wallet).filter(Boolean)).size,transactingWallets:wallets.size,qualifiedHandoffs:hands.length,mainnetHandoffs:test?0:hands.length,testnetHandoffs:test?hands.length:0,invites:Object.keys(this.state.invites).length,inviteConversions:Object.values(this.state.invites).filter(i=>i.claimedBy).length,returningWallets:Object.values(this.state.members).filter(m=>m.days.length>1).length,quickRematches:this.state.rematches,crewActiveDays:Object.values(this.state.crewDays).reduce((n,days)=>n+Object.keys(days).length,0),dailyAttempts:Object.values(this.state.daily).reduce((n,d)=>n+Object.keys(d).length,0),foregroundSeconds:Object.values(this.state.members).reduce((n,m)=>n+m.foreground,0),controlledEvidence:{handoffs:test?hands.length:0,wallets:test?wallets.size:0},definitions:['Wallets are linked accounts, not verified unique humans.','Qualified handoffs require independent chain verification and canonical replay.','All TestAlbatross activity is test evidence, excluded from mainnet traction.','Countries are consented network observations, VPN-sensitive; unknown locations are not inferred.','Returning wallets were active on more than one UTC day.','Foreground time is bounded server-observed authenticated heartbeats.']} }
  private snapshot(profile: Profile | null): NetworkSnapshot {
    const now=Date.now(), midnight=Math.floor(now/86400000)*86400000, daily=this.daily(profile)
    const crews=this.product.crews.map(c=>{const days=this.state.crewDays[c.id]??{};let streak=0,cursor=days[day()]?midnight:midnight-86400000;while(days[new Date(cursor).toISOString().slice(0,10)]){streak++;cursor-=86400000}let best=0,current=0,previous=0;for(const date of Object.keys(days).sort()){const t=Date.parse(date);current=t-previous===86400000?current+1:1;best=Math.max(best,current);previous=t}const contributions:Record<string,number>={};for(const h of this.state.handoffs)if(this.state.batons[h.batonId]?.crewId===c.id&&h.qualified)contributions[h.from.id]=(contributions[h.from.id]??0)+1;return {id:c.id,code:c.code,name:c.name,members:c.members.map(id=>this.product.players[id]).filter((p):p is Profile=>!!p).map(p=>this.runner(p)),batonIds:Object.values(this.state.batons).filter(b=>b.crewId===c.id).map(b=>b.id),streak,bestStreak:best,todayHandoffs:days[day()]??0,contributions,deadline:midnight+86400000}})
    return {network:this.env.NIMIQ_NETWORK,batons:Object.values(this.state.batons).sort((a,b)=>b.updatedAt-a.updatedAt).map(b=>({...b,route:[{countryCode:b.origin.country},...this.state.handoffs.filter(h=>h.batonId===b.id).map(h=>({countryCode:h.to.country}))]})),crews,rivals:this.state.rivals,daily,metrics:this.metrics(),playerId:profile?.id??null,runners:Object.keys(this.state.members).map(id=>this.product.players[id]).filter((p):p is Profile=>!!p).map(p=>this.runner(p)),inbox:profile?this.state.notifications[profile.id]??[]:[],invites:profile?Object.values(this.state.invites).filter(i=>i.from.id===profile.id||i.claimedBy===profile.id):[],pendingHandoff:profile?Object.values(this.state.intents).find(i=>i.sender===paymentAddress(profile.wallet)&&['prepared','attempting','submitted'].includes(i.state))??null:null,countryConsent:profile?this.state.members[profile.id]?.consent??false:false}
  }
  async handle(path:string,body:unknown,profile:Profile|null,country?:string):Promise<unknown> {
    if(path==='/public')return this.snapshot(null)
    if(path.startsWith('/batons/'))return this.detail(this.baton(decodeURIComponent(path.slice(8))),profile)
    if(path.startsWith('/replays/')){const ghost=await this.ghost(path.slice(9));if(!ghost)throw new ApiError('verified_replay_not_found',404);return ghost}
    if(path.startsWith('/invites/')){const token=path.slice(9);const invite=this.state.invites[await tokenHash(token)];if(!invite)throw new ApiError('invite_not_found',404);if(invite.expiresAt<Date.now())throw new ApiError('invite_expired',410);return invite}
    if(!profile)throw new ApiError('sign_in_to_join',401)
    const now=Date.now(), date=day(), member=this.state.members[profile.id]??={consent:false,country:null,firstSeen:now,lastSeen:now,days:[],foreground:0,lastHeartbeat:now}
    member.lastSeen=now;if(!member.days.includes(date))member.days.push(date)
    if(member.consent&&country&&/^[A-Z]{2}$/.test(country)&&!['XX','T1'].includes(country))member.country=country
    if(path==='/')return this.snapshot(profile)
    if(path==='/consent'){member.consent=z.object({consent:z.boolean()}).parse(body).consent;if(!member.consent)member.country=null;else if(country&&/^[A-Z]{2}$/.test(country)&&!['XX','T1'].includes(country))member.country=country;return this.snapshot(profile)}
    if(path==='/heartbeat'){const seconds=z.object({seconds:z.number().int().min(0).max(30)}).parse(body).seconds;member.foreground+=Math.min(seconds,Math.max(0,Math.floor((now-member.lastHeartbeat)/1000)),30);member.lastHeartbeat=now;return {ok:true}}
    if(path==='/create'){const input=z.object({mode:z.enum(['quick','global','crew','rival']),title:z.string().trim().min(3).max(60),recipient:z.string().optional(),bestOf:z.union([z.literal(3),z.literal(5)]).optional(),crewId:z.string().optional()}).parse(body);return this.detail(this.create(profile,input),profile)}
    if(path==='/rematch'){const {batonId}=z.object({batonId:z.string()}).parse(body), original=this.baton(batonId);if(!original.quick||!original.quick.players.includes(profile.id))throw new ApiError('match_not_found',404);if(original.status==='active')throw new ApiError('finish_match_first',409);const recipient=original.quick.players.find(id=>id!==profile.id)!;this.state.rematches++;return this.detail(this.create(profile,{mode:'quick',title:original.title,bestOf:original.quick.bestOf,recipient},original.id),profile)}
    if(path==='/issue')return this.issue(profile,body)
    if(path==='/handoff/prepare')return this.prepare(profile,body)
    if(path==='/handoff/attempt'){const {id}=idBody.parse(body),intent=this.intent(id,profile);if(intent.state==='prepared'){if(intent.expiresAt<now)throw new ApiError('handoff_expired',410);intent.state='attempting';intent.attemptedAt=now} else if(intent.state!=='attempting')throw new ApiError('handoff_not_sendable',409);await this.storage.setAlarm(now+15000);return intent}
    if(path==='/handoff/cancel'){const {id}=idBody.parse(body),intent=this.intent(id,profile);if(intent.state!=='prepared')throw new ApiError('check_wallet_before_rerouting',409);intent.state='cancelled';return intent}
    if(path==='/handoff/confirm'){const {id,txHash}=z.object({id:z.string().uuid(),txHash:z.string().regex(/^[a-f0-9]{64}$/i)}).parse(body);const intent=this.intent(id,profile);if(intent.txHash&&intent.txHash!==txHash.toLowerCase())throw new ApiError('different_transaction',409);if(!['attempting','submitted','verified'].includes(intent.state))throw new ApiError('handoff_not_attempted',409);intent.txHash=txHash.toLowerCase();if(intent.state!=='verified')intent.state='submitted';await this.persist();return this.confirm(intent)}
    if(path==='/invite'){const {batonId}=z.object({batonId:z.string()}).parse(body),baton=this.baton(batonId);this.holder(baton,profile);if(Object.values(this.state.invites).filter(i=>i.from.id===profile.id&&i.expiresAt>now).length>=20)throw new ApiError('too_many_active_invites',429);const token=crypto.randomUUID().replaceAll('-','')+crypto.randomUUID().replaceAll('-','');const invite:NetworkInvite={id:crypto.randomUUID(),token,batonId:baton.id,from:this.runner(profile),recipientId:baton.recipientId,createdAt:now,expiresAt:now+86400000,claimedBy:null,url:`${this.env.APP_ORIGIN}/invite/${token}`};this.state.invites[await tokenHash(token)]={...invite,token:'',url:''};return invite}
    if(path==='/invite/claim'){const {token}=z.object({token:z.string()}).parse(body),invite=this.state.invites[await tokenHash(token)];if(!invite||invite.expiresAt<now)throw new ApiError('invite_expired',410);if(invite.claimedBy&&invite.claimedBy!==profile.id)throw new ApiError('invite_already_claimed',409);if(invite.from.id===profile.id)throw new ApiError('invite_is_for_another_courier');if(invite.recipientId&&invite.recipientId!==profile.id)throw new ApiError('invite_is_for_another_courier',403);const baton=this.baton(invite.batonId);if(baton.holder.id!==invite.from.id||baton.status==='completed')throw new ApiError('invite_no_longer_current',410);if(this.pending(baton.id))throw new ApiError('handoff_already_prepared',409);invite.claimedBy=profile.id;baton.recipientId=profile.id;this.notify(baton.holder.id,'your_turn',`${profile.name} accepted`, 'Your next runner is ready for the baton.',baton.id);return this.detail(baton,profile)}
    if(path==='/crew/create'){const {name}=z.object({name:z.string().trim().min(3).max(28)}).parse(body);if(profile.crewId)throw new ApiError('already_in_a_crew',409);const crew={id:crypto.randomUUID(),name,code:shortCode(),members:[profile.id]};this.product.crews.push(crew);profile.crewId=crew.id;return this.snapshot(profile)}
    if(path==='/crew/join'){const {code}=z.object({code:z.string()}).parse(body),crew=this.product.crews.find(c=>c.code===code.trim().toUpperCase());if(!crew)throw new ApiError('crew_not_found',404);if(profile.crewId&&profile.crewId!==crew.id)throw new ApiError('already_in_a_crew',409);if(!crew.members.includes(profile.id)){if(crew.members.length>=5)throw new ApiError('crew_is_full',409);crew.members.push(profile.id)}profile.crewId=crew.id;return this.snapshot(profile)}
    if(path==='/rival/create'){const input=z.object({title:z.string().trim().min(3).max(60),opponent:z.string(),target:z.number().int().min(2).max(50).default(10)}).parse(body),other=this.other(input.opponent,profile),id=crypto.randomUUID();const a=this.create(profile,{mode:'rival',title:`${input.title} · ${profile.name}`}),b=this.create(other,{mode:'rival',title:`${input.title} · ${other.name}`});a.rivalId=id;b.rivalId=id;this.state.rivals.push({id,title:input.title,batonIds:[a.id,b.id],target:input.target,scores:[0,0],winnerId:null,createdAt:now,endsAt:now+7*86400000});this.notify(other.id,'rival_update',`${profile.name} started a rivalry`,input.title,b.id);return this.snapshot(profile)}
    if(path==='/inbox/read'){const {id}=idBody.parse(body);const item=this.state.notifications[profile.id]?.find(n=>n.id===id);if(item)item.readAt=now;return this.snapshot(profile)}
    throw new ApiError('not_found',404)
  }
  private intent(id:string,profile:Profile){const intent=this.state.intents[id];if(!intent||intent.sender!==paymentAddress(profile.wallet))throw new ApiError('handoff_not_found',404);return intent}
  private async issue(profile:Profile,body:unknown):Promise<IssuedRace>{
    const input=z.object({batonId:z.string().optional(),daily:z.boolean().optional(),practice:z.boolean().optional(),ghostRunId:z.string().optional()}).parse(body),baton=input.batonId?this.baton(input.batonId):null
    if(baton&&!input.practice)this.holder(baton,profile)
    const daily=this.daily(profile);if(input.daily&&!input.practice&&daily.officialRunId)throw new ApiError('official_daily_already_started',409)
    const ghost=await this.ghost(input.ghostRunId??baton?.previousRunId??null),world=ghost?.config.world??(input.daily?daily.world:baton?.world??'coast'),seed=ghost?.config.seed??(input.daily?daily.seed:baton?`baton-${baton.code}-v4`:crypto.randomUUID())
    if(input.ghostRunId&&!input.practice)throw new ApiError('selected_ghost_is_practice_only')
    const issued:IssuedRace={networkRace:true,practice:input.practice??false,...(baton?{batonId:baton.id}:{}),relayLeg:baton?.handoffCount??null,runId:crypto.randomUUID(),playerId:profile.id,mode:input.daily?'daily':baton?.mode??'quick',config:{engineVersion:'4',challenge:'station-race',challengeVersion:'4',seed,world},expiresAt:Date.now()+10*60000,target:null,mac:'',ghost}
    issued.mac=await mac(this.env.RUN_CHALLENGE_SECRET,signedFields(issued));await this.storage.put(`issue:${issued.runId}`,issued);if(input.daily&&!input.practice)this.state.dailyIssues[`${day()}:${profile.id}`]=issued.runId;return issued
  }
  async onRun(run:Run,profile:Profile){if(run.issued.practice)return;const baton=run.issued.batonId?this.baton(run.issued.batonId):null;if(baton){this.holder(baton,profile);if(baton.handoffCount!==run.issued.relayLeg)throw new ApiError('relay_leg_changed',409)}
    if(run.issued.mode==='daily'){const date=run.issued.config.seed.slice(6,16);if(this.state.dailyIssues[`${date}:${profile.id}`]!==run.issued.runId)throw new ApiError('not_official_daily');const results=this.state.daily[date]??={};results[profile.id]={runId:run.issued.runId,score:run.result.score,timeMs:run.result.timeMs}}

  }
  private async prepare(profile:Profile,body:unknown){const input=z.object({runId:z.string(),recipient:z.string(),throw:z.object({angle:z.number().int().min(15).max(75),power:z.number().int().min(30).max(100)}).default({angle:45,power:75})}).parse(body),run=await this.storage.get<Run>(`run:${input.runId}`);if(!run||run.issued.playerId!==profile.id||!run.issued.batonId||run.issued.practice||!run.result.completed)throw new ApiError('finish_your_relay_leg_first',409);const baton=this.baton(run.issued.batonId);this.holder(baton,profile);if(run.issued.relayLeg!==baton.handoffCount)throw new ApiError('relay_leg_changed',409);const other=this.other(input.recipient,profile);if(baton.quick&&!baton.quick.players.includes(other.id))throw new ApiError('pass_to_match_opponent');if(baton.crewId&&!this.product.crews.find(c=>c.id===baton.crewId)?.members.includes(other.id))throw new ApiError('choose_a_crew_member');if(baton.recipientId&&baton.recipientId!==other.id)throw new ApiError('recipient_reserved',409)
    const pending=this.pending(baton.id);if(pending){if(pending.runId!==input.runId||pending.recipientId!==other.id)throw new ApiError('handoff_already_prepared',409);return pending}
    const id=crypto.randomUUID(),leg=baton.handoffCount+1,commitment=await deriveCommitment(await mac(this.env.RUN_CHALLENGE_SECRET,{id,batonId:baton.id,leg,runId:input.runId,from:profile.id,to:other.id,throw:input.throw}));const intent:NetworkHandoffIntent={id,batonId:baton.id,runId:input.runId,recipientId:other.id,recipientName:other.name,sender:paymentAddress(profile.wallet),recipient:paymentAddress(other.wallet),value:baton.value,data:encodeTxData({relayCode:baton.code,legNumber:leg,commitment}),network:baton.network,leg,status:'pending',state:'prepared',txHash:null,throw:input.throw,createdAt:Date.now(),expiresAt:Date.now()+5*60000,attemptedAt:null,failure:null};this.state.intents[id]=intent;await this.storage.setAlarm(Date.now()+15000);return intent
  }
  private async confirm(intent:NetworkHandoffIntent):Promise<import('@nim-relay/shared').NetworkConfirmation>{
    const baton=this.baton(intent.batonId);if(intent.state==='verified')return{status:'verified',intent,baton};if(!intent.txHash)return{status:'pending',reason:'Check your wallet for the transfer reference',intent}
    if(this.product.usedTx[intent.txHash]&&this.product.usedTx[intent.txHash]!==intent.id)throw new ApiError('transaction_already_used',409)
    if(baton.handoffCount+1!==intent.leg||baton.holder.wallet!==intent.sender)throw new ApiError('custody_changed',409)
    try {const tx=await new NimiqRpcClient({rpcUrl:this.env.NIMIQ_RPC_URL}).getTransactionByHash(intent.txHash);if(tx.hash.toLowerCase()!==intent.txHash)throw new Error('Transaction hash mismatch');const proof=verifyHandoffTransaction(tx,{senderWallet:intent.sender,recipientWallet:intent.recipient,valueLuna:BigInt(intent.value),relayCode:baton.code,legNumber:intent.leg,commitment:intent.data.split('.')[3]!,network:baton.network,minConfirmations:2});if(!proof.ok){intent.failure=proof.reason;await this.storage.setAlarm(Date.now()+15000);return{status:['NOT_INCLUDED','INSUFFICIENT_CONFIRMATIONS'].includes(proof.reason)?'pending':'rejected',reason:proof.detail,intent}}
      const from=this.product.players[baton.holder.id]!,to=this.product.players[intent.recipientId]!,run=await this.storage.get<Run>(`run:${intent.runId}`);if(!run||!run.result.completed)throw new Error('Canonical relay run unavailable');const now=Date.now();this.state.handoffs.push({id:intent.id,batonId:baton.id,leg:intent.leg,from:this.runner(from),to:this.runner(to),value:intent.value,txHash:intent.txHash,network:baton.network,at:now,runId:intent.runId,resultHash:run.result.resultHash,qualified:true,confirmations:proof.confirmations,blockNumber:proof.blockNumber});intent.state='verified';intent.status='verified';intent.failure=null;this.product.usedTx[intent.txHash]=intent.id;baton.holder=this.runner(to);baton.handoffCount=intent.leg;baton.updatedAt=now;baton.expiresAt=now+86400000;baton.status='active';baton.previousRunId=intent.runId;baton.recipientId=baton.quick?from.id:null
      const hands=this.state.handoffs.filter(h=>h.batonId===baton.id);baton.lineage.countries=[...new Set(hands.flatMap(h=>[h.from.country,h.to.country]).filter((c):c is string=>!!c))];baton.lineage.runners=new Set(hands.flatMap(h=>[h.from.id,h.to.id])).size
      if(run.issued.ghost&&run.result.score>run.issued.ghost.result.score){baton.lineage.ghostWins++;const previous=await this.storage.get<Run>(`run:${run.issued.ghost.runId}`);if(previous)this.notify(previous.issued.playerId,'ghost_beaten',`${from.name} beat your ghost`,baton.title,baton.id,intent.runId)}
      from.handoffs++;from.xp+=250;from.level=1+Math.floor(from.xp/500);if(!from.achievements.includes('Baton bearer'))from.achievements.push('Baton bearer')
      if(baton.crewId){const days=this.state.crewDays[baton.crewId]??={};days[day()]=(days[day()]??0)+1}
      if(baton.quick&&intent.leg%2===0){const pair=hands.slice(-2);const first=await this.storage.get<Run>(`run:${pair[0]!.runId}`);const second=run;const winner=first&&first.result.score>second.result.score?pair[0]!.from.id:first&&first.result.score===second.result.score?null:pair[1]!.from.id;if(winner)baton.quick.scores[winner]=(baton.quick.scores[winner]??0)+1;baton.quick.rounds++;const winnerId=Object.keys(baton.quick.scores).find(id=>baton.quick!.scores[id]!>baton.quick!.bestOf/2);if(winnerId||baton.quick.rounds>=baton.quick.bestOf){baton.quick.winnerId=winnerId??(baton.quick.scores[baton.quick.players[0]!]===baton.quick.scores[baton.quick.players[1]!]?null:baton.quick.players.reduce((best,id)=>baton.quick!.scores[id]!>baton.quick!.scores[best]!?id:best));baton.status='completed'}}
      if(baton.rivalId){const rival=this.state.rivals.find(r=>r.id===baton.rivalId)!;rival.scores=[this.baton(rival.batonIds[0]).handoffCount,this.baton(rival.batonIds[1]).handoffCount];if(!rival.winnerId&&baton.handoffCount>=rival.target){rival.winnerId=baton.id;for(const id of rival.batonIds)this.baton(id).status='completed'}if(rival.winnerId)baton.status='completed';this.notify(to.id,'rival_update','Your team’s baton moved',rival.title,baton.id)}
      this.notify(to.id,'incoming_baton',`${from.name} passed you the baton`,`${baton.title} · Handoff ${intent.leg}`,baton.id,intent.runId);await this.persist();return{status:'verified',intent,baton}
    }catch(error){intent.failure=error instanceof Error?error.message:'Verification unavailable';await this.storage.setAlarm(Date.now()+15000);return{status:'pending',reason:'Waiting for independent network confirmation',intent}}
  }
  async reconcile(){const now=Date.now();for(const intent of Object.values(this.state.intents)){if(intent.state==='prepared'&&intent.expiresAt<now)intent.state='expired';if(intent.state==='submitted')await this.confirm(intent)}for(const baton of Object.values(this.state.batons))if(baton.status==='active'&&baton.expiresAt<now&&!this.pending(baton.id))baton.status='stranded';await this.persist(false);await this.archive();await this.storage.transaction(storage=>this.writeTo(storage));if(this.state.dirty||Object.values(this.state.intents).some(i=>['prepared','attempting','submitted'].includes(i.state))||Object.values(this.state.batons).some(b=>b.status==='active'))await this.storage.setAlarm(now+30000)}
  async persist(schedule=true){this.state.version++;this.state.dirty=true;await this.storage.transaction(async storage=>{await this.writeTo(storage);await storage.put('state',this.product)});if(schedule)await this.storage.setAlarm(Date.now()+15000)}
  private async archive(){if(!this.env.SUPABASE_URL||!this.env.SUPABASE_SERVICE_ROLE_KEY)return;const client=createClient(this.env.SUPABASE_URL,this.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false}});const {error}=await client.from('relay_network_snapshots').upsert({network:this.env.NIMIQ_NETWORK,version:this.state.version,payload:this.state,updated_at:new Date().toISOString()},{onConflict:'network'});if(error){console.error('Network archive deferred',error.code);return}for(const handoff of this.state.handoffs){const result=await client.from('relay_network_handoffs').upsert({id:handoff.id,network:handoff.network,baton_id:handoff.batonId,leg:handoff.leg,tx_hash:handoff.txHash,payload:handoff},{onConflict:'id',ignoreDuplicates:true});if(result.error){console.error('Handoff archive deferred',result.error.code);return}}this.state.dirty=false}
}
